Shader "Hidden/FastBloom" {
Properties {
 _MainTex ("Base (RGB)", 2D) = "white" { }
 _Bloom ("Bloom (RGB)", 2D) = "black" { }
}
SubShader { 
 Pass {
  ZTest False
  ZWrite Off
  Cull Off
  Fog { Mode Off }
  GpuProgramID 32358
Program "vp" {
SubProgram "opengl " {
"!!GLSL
#ifdef VERTEX

varying vec2 xlv_TEXCOORD0;
void main ()
{
  gl_Position = (gl_ModelViewProjectionMatrix * gl_Vertex);
  xlv_TEXCOORD0 = gl_MultiTexCoord0.xy;
}


#endif
#ifdef FRAGMENT
uniform sampler2D _MainTex;
uniform sampler2D _Bloom;
varying vec2 xlv_TEXCOORD0;
void main ()
{
  gl_FragData[0] = (texture2D (_MainTex, xlv_TEXCOORD0) + texture2D (_Bloom, xlv_TEXCOORD0));
}


#endif
"
}
SubProgram "d3d9 " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
Matrix 0 [glstate_matrix_mvp]
Vector 4 [_MainTex_TexelSize]
"vs_2_0
def c5, 0, -2, 1, 0
dcl_position v0
dcl_texcoord v1
dp4 oPos.x, c0, v0
dp4 oPos.y, c1, v0
dp4 oPos.z, c2, v0
dp4 oPos.w, c3, v0
mov r0.x, c5.x
slt r0.x, c4.y, r0.x
mad r0.y, v1.y, c5.y, c5.z
mad oT0.y, r0.x, r0.y, v1.y
mov oT0.x, v1.x
mov oT1.xy, v1

"
}
SubProgram "d3d11 " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 160
Vector 96 [_MainTex_TexelSize]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefieceddcdckodlfdmnaffnjmgamajikfngjhgjabaaaaaahmacaaaaadaaaaaa
cmaaaaaaiaaaaaaapaaaaaaaejfdeheoemaaaaaaacaaaaaaaiaaaaaadiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaaebaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaafaepfdejfeejepeoaafeeffiedepepfceeaaklkl
epfdeheogiaaaaaaadaaaaaaaiaaaaaafaaaaaaaaaaaaaaaabaaaaaaadaaaaaa
aaaaaaaaapaaaaaafmaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaa
fmaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaaamadaaaafdfgfpfaepfdejfe
ejepeoaafeeffiedepepfceeaaklklklfdeieefcieabaaaaeaaaabaagbaaaaaa
fjaaaaaeegiocaaaaaaaaaaaahaaaaaafjaaaaaeegiocaaaabaaaaaaaeaaaaaa
fpaaaaadpcbabaaaaaaaaaaafpaaaaaddcbabaaaabaaaaaaghaaaaaepccabaaa
aaaaaaaaabaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaa
giaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaaegiocaaa
abaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaaaaaaaaa
agbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpccabaaa
aaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaaaaaaaaaa
dbaaaaaibcaabaaaaaaaaaaabkiacaaaaaaaaaaaagaaaaaaabeaaaaaaaaaaaaa
aaaaaaaiccaabaaaaaaaaaaabkbabaiaebaaaaaaabaaaaaaabeaaaaaaaaaiadp
dhaaaaajcccabaaaabaaaaaaakaabaaaaaaaaaaabkaabaaaaaaaaaaabkbabaaa
abaaaaaadgaaaaafnccabaaaabaaaaaaagbebaaaabaaaaaadoaaaaab"
}
SubProgram "d3d11_9x " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 160
Vector 96 [_MainTex_TexelSize]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0_level_9_1
eefiecedghdmcbnceclfbhbmihpgnhmopgafiacoabaaaaaalmadaaaaaeaaaaaa
daaaaaaagmabaaaapiacaaaaemadaaaaebgpgodjdeabaaaadeabaaaaaaacpopp
peaaaaaaeaaaaaaaacaaceaaaaaadmaaaaaadmaaaaaaceaaabaadmaaaaaaagaa
abaaabaaaaaaaaaaabaaaaaaaeaaacaaaaaaaaaaaaaaaaaaaaacpoppfbaaaaaf
agaaapkaaaaaaaaaaaaaaamaaaaaiadpaaaaaaaabpaaaaacafaaaaiaaaaaapja
bpaaaaacafaaabiaabaaapjaabaaaaacaaaaabiaagaaaakaamaaaaadaaaaabia
abaaffkaaaaaaaiaaeaaaaaeaaaaaciaabaaffjaagaaffkaagaakkkaaeaaaaae
aaaaacoaaaaaaaiaaaaaffiaabaaffjaafaaaaadaaaaapiaaaaaffjaadaaoeka
aeaaaaaeaaaaapiaacaaoekaaaaaaajaaaaaoeiaaeaaaaaeaaaaapiaaeaaoeka
aaaakkjaaaaaoeiaaeaaaaaeaaaaapiaafaaoekaaaaappjaaaaaoeiaaeaaaaae
aaaaadmaaaaappiaaaaaoekaaaaaoeiaabaaaaacaaaaammaaaaaoeiaabaaaaac
aaaaanoaabaabejappppaaaafdeieefcieabaaaaeaaaabaagbaaaaaafjaaaaae
egiocaaaaaaaaaaaahaaaaaafjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaad
pcbabaaaaaaaaaaafpaaaaaddcbabaaaabaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaaabaaaaaagiaaaaac
abaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaaegiocaaaabaaaaaa
abaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaaaaaaaaaagbabaaa
aaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaa
acaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpccabaaaaaaaaaaa
egiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaaaaaaaaaadbaaaaai
bcaabaaaaaaaaaaabkiacaaaaaaaaaaaagaaaaaaabeaaaaaaaaaaaaaaaaaaaai
ccaabaaaaaaaaaaabkbabaiaebaaaaaaabaaaaaaabeaaaaaaaaaiadpdhaaaaaj
cccabaaaabaaaaaaakaabaaaaaaaaaaabkaabaaaaaaaaaaabkbabaaaabaaaaaa
dgaaaaafnccabaaaabaaaaaaagbebaaaabaaaaaadoaaaaabejfdeheoemaaaaaa
acaaaaaaaiaaaaaadiaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaa
ebaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadadaaaafaepfdejfeejepeo
aafeeffiedepepfceeaaklklepfdeheogiaaaaaaadaaaaaaaiaaaaaafaaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaafmaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadamaaaafmaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amadaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaklklkl"
}
}
Program "fp" {
SubProgram "opengl " {
"!!GLSL"
}
SubProgram "d3d9 " {
SetTexture 0 [_MainTex] 2D 0
SetTexture 1 [_Bloom] 2D 1
"ps_2_0
dcl_pp t0.xy
dcl_pp t1.xy
dcl_2d s0
dcl_2d s1
texld_pp r0, t0, s0
texld r1, t1, s1
add_pp r0, r0, r1
mov_pp oC0, r0

"
}
SubProgram "d3d11 " {
SetTexture 0 [_MainTex] 2D 0
SetTexture 1 [_Bloom] 2D 1
"ps_4_0
eefiecedbajopjkjnkjfmkiajdgfmeknkcigdlnmabaaaaaakmabaaaaadaaaaaa
cmaaaaaajmaaaaaanaaaaaaaejfdeheogiaaaaaaadaaaaaaaiaaaaaafaaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaafmaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaafmaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaklklklepfdeheo
cmaaaaaaabaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaa
apaaaaaafdfgfpfegbhcghgfheaaklklfdeieefcneaaaaaaeaaaaaaadfaaaaaa
fkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaaabaaaaaafibiaaaeaahabaaa
aaaaaaaaffffaaaafibiaaaeaahabaaaabaaaaaaffffaaaagcbaaaaddcbabaaa
abaaaaaagcbaaaadmcbabaaaabaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaac
acaaaaaaefaaaaajpcaabaaaaaaaaaaaegbabaaaabaaaaaaeghobaaaaaaaaaaa
aagabaaaaaaaaaaaefaaaaajpcaabaaaabaaaaaaogbkbaaaabaaaaaaeghobaaa
abaaaaaaaagabaaaabaaaaaaaaaaaaahpccabaaaaaaaaaaaegaobaaaaaaaaaaa
egaobaaaabaaaaaadoaaaaab"
}
SubProgram "d3d11_9x " {
SetTexture 0 [_MainTex] 2D 0
SetTexture 1 [_Bloom] 2D 1
"ps_4_0_level_9_1
eefiecedafmkjpfjklcgnpbbbpofgkloedhflgaoabaaaaaafiacaaaaaeaaaaaa
daaaaaaaniaaaaaaleabaaaaceacaaaaebgpgodjkaaaaaaakaaaaaaaaaacpppp
heaaaaaacmaaaaaaaaaacmaaaaaacmaaaaaacmaaacaaceaaaaaacmaaaaaaaaaa
abababaaaaacppppbpaaaaacaaaaaaiaaaaacplabpaaaaacaaaaaajaaaaiapka
bpaaaaacaaaaaajaabaiapkaabaaaaacaaaacdiaaaaabllaecaaaaadaaaaapia
aaaaoeiaabaioekaecaaaaadabaacpiaaaaaoelaaaaioekaacaaaaadaaaacpia
aaaaoeiaabaaoeiaabaaaaacaaaicpiaaaaaoeiappppaaaafdeieefcneaaaaaa
eaaaaaaadfaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaaabaaaaaa
fibiaaaeaahabaaaaaaaaaaaffffaaaafibiaaaeaahabaaaabaaaaaaffffaaaa
gcbaaaaddcbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagfaaaaadpccabaaa
aaaaaaaagiaaaaacacaaaaaaefaaaaajpcaabaaaaaaaaaaaegbabaaaabaaaaaa
eghobaaaaaaaaaaaaagabaaaaaaaaaaaefaaaaajpcaabaaaabaaaaaaogbkbaaa
abaaaaaaeghobaaaabaaaaaaaagabaaaabaaaaaaaaaaaaahpccabaaaaaaaaaaa
egaobaaaaaaaaaaaegaobaaaabaaaaaadoaaaaabejfdeheogiaaaaaaadaaaaaa
aiaaaaaafaaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaafmaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadadaaaafmaaaaaaabaaaaaaaaaaaaaa
adaaaaaaabaaaaaaamamaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfcee
aaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgfheaaklkl"
}
}
 }
 Pass {
  ZTest False
  ZWrite Off
  Cull Off
  Fog { Mode Off }
  GpuProgramID 130822
Program "vp" {
SubProgram "opengl " {
"!!GLSL
#ifdef VERTEX

uniform vec4 _MainTex_TexelSize;
varying vec2 xlv_TEXCOORD0;
varying vec2 xlv_TEXCOORD1;
varying vec2 xlv_TEXCOORD2;
varying vec2 xlv_TEXCOORD3;
void main ()
{
  gl_Position = (gl_ModelViewProjectionMatrix * gl_Vertex);
  xlv_TEXCOORD0 = (gl_MultiTexCoord0.xy + _MainTex_TexelSize.xy);
  xlv_TEXCOORD1 = (gl_MultiTexCoord0.xy + (_MainTex_TexelSize.xy * vec2(-0.5, -0.5)));
  xlv_TEXCOORD2 = (gl_MultiTexCoord0.xy + (_MainTex_TexelSize.xy * vec2(0.5, -0.5)));
  xlv_TEXCOORD3 = (gl_MultiTexCoord0.xy + (_MainTex_TexelSize.xy * vec2(-0.5, 0.5)));
}


#endif
#ifdef FRAGMENT
uniform sampler2D _MainTex;
uniform vec4 _Parameter;
varying vec2 xlv_TEXCOORD0;
varying vec2 xlv_TEXCOORD1;
varying vec2 xlv_TEXCOORD2;
varying vec2 xlv_TEXCOORD3;
void main ()
{
  gl_FragData[0] = (max ((
    ((((texture2D (_MainTex, xlv_TEXCOORD0) + texture2D (_MainTex, xlv_TEXCOORD1)) + texture2D (_MainTex, xlv_TEXCOORD2)) + texture2D (_MainTex, xlv_TEXCOORD3)) / 4.0)
   - _Parameter.z), vec4(0.0, 0.0, 0.0, 0.0)) * _Parameter.w);
}


#endif
"
}
SubProgram "d3d9 " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
Matrix 0 [glstate_matrix_mvp]
Vector 4 [_MainTex_TexelSize]
"vs_2_0
def c5, -0.5, 0.5, 0, 0
dcl_position v0
dcl_texcoord v1
dp4 oPos.x, c0, v0
dp4 oPos.y, c1, v0
dp4 oPos.z, c2, v0
dp4 oPos.w, c3, v0
add oT0.xy, v1, c4
mov r0.xy, c4
mad oT1.xy, r0, c5.x, v1
mad oT2.xy, r0, c5.yxzw, v1
mad oT3.xy, r0, c5, v1

"
}
SubProgram "d3d11 " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 160
Vector 96 [_MainTex_TexelSize]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedanminhenonglbeadkdnbcjjkaoaknlimabaaaaaaaiadaaaaadaaaaaa
cmaaaaaaiaaaaaaacaabaaaaejfdeheoemaaaaaaacaaaaaaaiaaaaaadiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaaebaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaafaepfdejfeejepeoaafeeffiedepepfceeaaklkl
epfdeheojiaaaaaaafaaaaaaaiaaaaaaiaaaaaaaaaaaaaaaabaaaaaaadaaaaaa
aaaaaaaaapaaaaaaimaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaa
imaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaaamadaaaaimaaaaaaacaaaaaa
aaaaaaaaadaaaaaaacaaaaaaadamaaaaimaaaaaaadaaaaaaaaaaaaaaadaaaaaa
acaaaaaaamadaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaklklkl
fdeieefcoaabaaaaeaaaabaahiaaaaaafjaaaaaeegiocaaaaaaaaaaaahaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaabaaaaaaghaaaaaepccabaaaaaaaaaaaabaaaaaagfaaaaaddccabaaa
abaaaaaagfaaaaadmccabaaaabaaaaaagfaaaaaddccabaaaacaaaaaagfaaaaad
mccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpccabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaaaaaaaaaidccabaaaabaaaaaaegbabaaaabaaaaaaegiacaaa
aaaaaaaaagaaaaaadcaaaaanmccabaaaabaaaaaaagiecaaaaaaaaaaaagaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaalpaaaaaalpagbebaaaabaaaaaadcaaaaan
dccabaaaacaaaaaaegiacaaaaaaaaaaaagaaaaaaaceaaaaaaaaaaadpaaaaaalp
aaaaaaaaaaaaaaaaegbabaaaabaaaaaadcaaaaanmccabaaaacaaaaaaagiecaaa
aaaaaaaaagaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaalpaaaaaadpagbebaaa
abaaaaaadoaaaaab"
}
SubProgram "d3d11_9x " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 160
Vector 96 [_MainTex_TexelSize]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0_level_9_1
eefiecedjgadclkdioiffafkojlidhlodlinbfplabaaaaaafaaeaaaaaeaaaaaa
daaaaaaaheabaaaafmadaaaalaadaaaaebgpgodjdmabaaaadmabaaaaaaacpopp
pmaaaaaaeaaaaaaaacaaceaaaaaadmaaaaaadmaaaaaaceaaabaadmaaaaaaagaa
abaaabaaaaaaaaaaabaaaaaaaeaaacaaaaaaaaaaaaaaaaaaaaacpoppfbaaaaaf
agaaapkaaaaaaalpaaaaaadpaaaaaaaaaaaaaaaabpaaaaacafaaaaiaaaaaapja
bpaaaaacafaaabiaabaaapjaacaaaaadaaaaadoaabaaoejaabaaoekaabaaaaac
aaaaadiaabaaoekaaeaaaaaeaaaaamoaaaaabeiaagaaaakaabaabejaaeaaaaae
abaaadoaaaaaoeiaagaaobkaabaaoejaaeaaaaaeabaaamoaaaaabeiaagaabeka
abaabejaafaaaaadaaaaapiaaaaaffjaadaaoekaaeaaaaaeaaaaapiaacaaoeka
aaaaaajaaaaaoeiaaeaaaaaeaaaaapiaaeaaoekaaaaakkjaaaaaoeiaaeaaaaae
aaaaapiaafaaoekaaaaappjaaaaaoeiaaeaaaaaeaaaaadmaaaaappiaaaaaoeka
aaaaoeiaabaaaaacaaaaammaaaaaoeiappppaaaafdeieefcoaabaaaaeaaaabaa
hiaaaaaafjaaaaaeegiocaaaaaaaaaaaahaaaaaafjaaaaaeegiocaaaabaaaaaa
aeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaaddcbabaaaabaaaaaaghaaaaae
pccabaaaaaaaaaaaabaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadmccabaaa
abaaaaaagfaaaaaddccabaaaacaaaaaagfaaaaadmccabaaaacaaaaaagiaaaaac
abaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaaegiocaaaabaaaaaa
abaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaaaaaaaaaagbabaaa
aaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaa
acaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpccabaaaaaaaaaaa
egiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaaaaaaaaaaaaaaaaai
dccabaaaabaaaaaaegbabaaaabaaaaaaegiacaaaaaaaaaaaagaaaaaadcaaaaan
mccabaaaabaaaaaaagiecaaaaaaaaaaaagaaaaaaaceaaaaaaaaaaaaaaaaaaaaa
aaaaaalpaaaaaalpagbebaaaabaaaaaadcaaaaandccabaaaacaaaaaaegiacaaa
aaaaaaaaagaaaaaaaceaaaaaaaaaaadpaaaaaalpaaaaaaaaaaaaaaaaegbabaaa
abaaaaaadcaaaaanmccabaaaacaaaaaaagiecaaaaaaaaaaaagaaaaaaaceaaaaa
aaaaaaaaaaaaaaaaaaaaaalpaaaaaadpagbebaaaabaaaaaadoaaaaabejfdeheo
emaaaaaaacaaaaaaaiaaaaaadiaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaa
apapaaaaebaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadadaaaafaepfdej
feejepeoaafeeffiedepepfceeaaklklepfdeheojiaaaaaaafaaaaaaaiaaaaaa
iaaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaimaaaaaaaaaaaaaa
aaaaaaaaadaaaaaaabaaaaaaadamaaaaimaaaaaaabaaaaaaaaaaaaaaadaaaaaa
abaaaaaaamadaaaaimaaaaaaacaaaaaaaaaaaaaaadaaaaaaacaaaaaaadamaaaa
imaaaaaaadaaaaaaaaaaaaaaadaaaaaaacaaaaaaamadaaaafdfgfpfaepfdejfe
ejepeoaafeeffiedepepfceeaaklklkl"
}
}
Program "fp" {
SubProgram "opengl " {
"!!GLSL"
}
SubProgram "d3d9 " {
Vector 0 [_Parameter]
SetTexture 0 [_MainTex] 2D 0
"ps_2_0
def c1, 0.25, 0, 0, 0
dcl_pp t0.xy
dcl_pp t1.xy
dcl_pp t2.xy
dcl_pp t3.xy
dcl_2d s0
texld_pp r0, t0, s0
texld r1, t1, s0
texld r2, t2, s0
texld r3, t3, s0
add_pp r0, r0, r1
add_pp r0, r2, r0
add_pp r0, r3, r0
mov r1.x, c1.x
mad_pp r0, r0, r1.x, -c0.z
mul_pp r1, r0, c0.w
cmp_pp r0, r0, r1, c1.y
mov_pp oC0, r0

"
}
SubProgram "d3d11 " {
SetTexture 0 [_MainTex] 2D 0
ConstBuffer "$Globals" 160
Vector 112 [_Parameter]
BindCB  "$Globals" 0
"ps_4_0
eefiecedgmblalkfccmhomajacfocncnfgeibnbpabaaaaaaoiacaaaaadaaaaaa
cmaaaaaammaaaaaaaaabaaaaejfdeheojiaaaaaaafaaaaaaaiaaaaaaiaaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaimaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaimaaaaaaabaaaaaaaaaaaaaaadaaaaaaabaaaaaa
amamaaaaimaaaaaaacaaaaaaaaaaaaaaadaaaaaaacaaaaaaadadaaaaimaaaaaa
adaaaaaaaaaaaaaaadaaaaaaacaaaaaaamamaaaafdfgfpfaepfdejfeejepeoaa
feeffiedepepfceeaaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaacaaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgfheaaklkl
fdeieefcoaabaaaaeaaaaaaahiaaaaaafjaaaaaeegiocaaaaaaaaaaaaiaaaaaa
fkaaaaadaagabaaaaaaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaagcbaaaad
dcbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagcbaaaaddcbabaaaacaaaaaa
gcbaaaadmcbabaaaacaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaacacaaaaaa
efaaaaajpcaabaaaaaaaaaaaegbabaaaabaaaaaaeghobaaaaaaaaaaaaagabaaa
aaaaaaaaefaaaaajpcaabaaaabaaaaaaogbkbaaaabaaaaaaeghobaaaaaaaaaaa
aagabaaaaaaaaaaaaaaaaaahpcaabaaaaaaaaaaaegaobaaaaaaaaaaaegaobaaa
abaaaaaaefaaaaajpcaabaaaabaaaaaaegbabaaaacaaaaaaeghobaaaaaaaaaaa
aagabaaaaaaaaaaaaaaaaaahpcaabaaaaaaaaaaaegaobaaaaaaaaaaaegaobaaa
abaaaaaaefaaaaajpcaabaaaabaaaaaaogbkbaaaacaaaaaaeghobaaaaaaaaaaa
aagabaaaaaaaaaaaaaaaaaahpcaabaaaaaaaaaaaegaobaaaaaaaaaaaegaobaaa
abaaaaaadcaaaaaopcaabaaaaaaaaaaaegaobaaaaaaaaaaaaceaaaaaaaaaiado
aaaaiadoaaaaiadoaaaaiadokgikcaiaebaaaaaaaaaaaaaaahaaaaaadeaaaaak
pcaabaaaaaaaaaaaegaobaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaadiaaaaaipccabaaaaaaaaaaaegaobaaaaaaaaaaapgipcaaaaaaaaaaa
ahaaaaaadoaaaaab"
}
SubProgram "d3d11_9x " {
SetTexture 0 [_MainTex] 2D 0
ConstBuffer "$Globals" 160
Vector 112 [_Parameter]
BindCB  "$Globals" 0
"ps_4_0_level_9_1
eefiecedpecbpijadgfnmijbmbklplkhflebhdjjabaaaaaaeeaeaaaaaeaaaaaa
daaaaaaaiiabaaaahaadaaaabaaeaaaaebgpgodjfaabaaaafaabaaaaaaacpppp
bmabaaaadeaaaaaaabaaciaaaaaadeaaaaaadeaaabaaceaaaaaadeaaaaaaaaaa
aaaaahaaabaaaaaaaaaaaaaaaaacppppfbaaaaafabaaapkaaaaaiadoaaaaaaaa
aaaaaaaaaaaaaaaabpaaaaacaaaaaaiaaaaacplabpaaaaacaaaaaaiaabaacpla
bpaaaaacaaaaaajaaaaiapkaabaaaaacaaaacdiaaaaabllaabaaaaacabaacdia
abaabllaecaaaaadaaaaapiaaaaaoeiaaaaioekaecaaaaadacaacpiaaaaaoela
aaaioekaecaaaaadadaaapiaabaaoelaaaaioekaecaaaaadabaaapiaabaaoeia
aaaioekaacaaaaadaaaacpiaaaaaoeiaacaaoeiaacaaaaadaaaacpiaadaaoeia
aaaaoeiaacaaaaadaaaacpiaabaaoeiaaaaaoeiaabaaaaacabaaabiaabaaaaka
aeaaaaaeaaaacpiaaaaaoeiaabaaaaiaaaaakkkbafaaaaadabaacpiaaaaaoeia
aaaappkafiaaaaaeaaaacpiaaaaaoeiaabaaoeiaabaaffkaabaaaaacaaaicpia
aaaaoeiappppaaaafdeieefcoaabaaaaeaaaaaaahiaaaaaafjaaaaaeegiocaaa
aaaaaaaaaiaaaaaafkaaaaadaagabaaaaaaaaaaafibiaaaeaahabaaaaaaaaaaa
ffffaaaagcbaaaaddcbabaaaabaaaaaagcbaaaadmcbabaaaabaaaaaagcbaaaad
dcbabaaaacaaaaaagcbaaaadmcbabaaaacaaaaaagfaaaaadpccabaaaaaaaaaaa
giaaaaacacaaaaaaefaaaaajpcaabaaaaaaaaaaaegbabaaaabaaaaaaeghobaaa
aaaaaaaaaagabaaaaaaaaaaaefaaaaajpcaabaaaabaaaaaaogbkbaaaabaaaaaa
eghobaaaaaaaaaaaaagabaaaaaaaaaaaaaaaaaahpcaabaaaaaaaaaaaegaobaaa
aaaaaaaaegaobaaaabaaaaaaefaaaaajpcaabaaaabaaaaaaegbabaaaacaaaaaa
eghobaaaaaaaaaaaaagabaaaaaaaaaaaaaaaaaahpcaabaaaaaaaaaaaegaobaaa
aaaaaaaaegaobaaaabaaaaaaefaaaaajpcaabaaaabaaaaaaogbkbaaaacaaaaaa
eghobaaaaaaaaaaaaagabaaaaaaaaaaaaaaaaaahpcaabaaaaaaaaaaaegaobaaa
aaaaaaaaegaobaaaabaaaaaadcaaaaaopcaabaaaaaaaaaaaegaobaaaaaaaaaaa
aceaaaaaaaaaiadoaaaaiadoaaaaiadoaaaaiadokgikcaiaebaaaaaaaaaaaaaa
ahaaaaaadeaaaaakpcaabaaaaaaaaaaaegaobaaaaaaaaaaaaceaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaadiaaaaaipccabaaaaaaaaaaaegaobaaaaaaaaaaa
pgipcaaaaaaaaaaaahaaaaaadoaaaaabejfdeheojiaaaaaaafaaaaaaaiaaaaaa
iaaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaimaaaaaaaaaaaaaa
aaaaaaaaadaaaaaaabaaaaaaadadaaaaimaaaaaaabaaaaaaaaaaaaaaadaaaaaa
abaaaaaaamamaaaaimaaaaaaacaaaaaaaaaaaaaaadaaaaaaacaaaaaaadadaaaa
imaaaaaaadaaaaaaaaaaaaaaadaaaaaaacaaaaaaamamaaaafdfgfpfaepfdejfe
ejepeoaafeeffiedepepfceeaaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaa
caaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgf
heaaklkl"
}
}
 }
 Pass {
  ZTest Always
  ZWrite Off
  Cull Off
  Fog { Mode Off }
  GpuProgramID 141954
Program "vp" {
SubProgram "opengl " {
"!!GLSL
#ifdef VERTEX

uniform vec4 _MainTex_TexelSize;
uniform vec4 _Parameter;
varying vec4 xlv_TEXCOORD0;
varying vec2 xlv_TEXCOORD1;
void main ()
{
  vec4 tmpvar_1;
  tmpvar_1.zw = vec2(1.0, 1.0);
  tmpvar_1.xy = gl_MultiTexCoord0.xy;
  gl_Position = (gl_ModelViewProjectionMatrix * gl_Vertex);
  xlv_TEXCOORD0 = tmpvar_1;
  xlv_TEXCOORD1 = ((_MainTex_TexelSize.xy * vec2(0.0, 1.0)) * _Parameter.x);
}


#endif
#ifdef FRAGMENT
uniform sampler2D _MainTex;
varying vec4 xlv_TEXCOORD0;
varying vec2 xlv_TEXCOORD1;
void main ()
{
  vec4 color_1;
  vec2 coords_2;
  coords_2 = (xlv_TEXCOORD0.xy - (xlv_TEXCOORD1 * 3.0));
  color_1 = (texture2D (_MainTex, coords_2) * vec4(0.0205, 0.0205, 0.0205, 0.0));
  coords_2 = (coords_2 + xlv_TEXCOORD1);
  color_1 = (color_1 + (texture2D (_MainTex, coords_2) * vec4(0.0855, 0.0855, 0.0855, 0.0)));
  coords_2 = (coords_2 + xlv_TEXCOORD1);
  color_1 = (color_1 + (texture2D (_MainTex, coords_2) * vec4(0.232, 0.232, 0.232, 0.0)));
  coords_2 = (coords_2 + xlv_TEXCOORD1);
  color_1 = (color_1 + (texture2D (_MainTex, coords_2) * vec4(0.324, 0.324, 0.324, 1.0)));
  coords_2 = (coords_2 + xlv_TEXCOORD1);
  color_1 = (color_1 + (texture2D (_MainTex, coords_2) * vec4(0.232, 0.232, 0.232, 0.0)));
  coords_2 = (coords_2 + xlv_TEXCOORD1);
  color_1 = (color_1 + (texture2D (_MainTex, coords_2) * vec4(0.0855, 0.0855, 0.0855, 0.0)));
  coords_2 = (coords_2 + xlv_TEXCOORD1);
  color_1 = (color_1 + (texture2D (_MainTex, coords_2) * vec4(0.0205, 0.0205, 0.0205, 0.0)));
  coords_2 = (coords_2 + xlv_TEXCOORD1);
  gl_FragData[0] = color_1;
}


#endif
"
}
SubProgram "d3d9 " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
Matrix 0 [glstate_matrix_mvp]
Vector 4 [_MainTex_TexelSize]
Vector 5 [_Parameter]
"vs_2_0
def c6, 1, 0, 0, 0
dcl_position v0
dcl_texcoord v1
dp4 oPos.x, c0, v0
dp4 oPos.y, c1, v0
dp4 oPos.z, c2, v0
dp4 oPos.w, c3, v0
mov r0.xy, c6
mul r0, r0.xyyx, c5.x
add r0.xy, r0, c6.yxzw
mul r0.xy, r0, c4
mul oT1.xy, r0.zwzw, r0
mad oT0, v1.xyxx, c6.xxyy, c6.yyxx

"
}
SubProgram "d3d11 " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 160
Vector 96 [_MainTex_TexelSize]
Vector 112 [_Parameter]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedfnmdkbhjnbhcnaiclfijfccngnianedfabaaaaaakmacaaaaadaaaaaa
cmaaaaaaiaaaaaaapaaaaaaaejfdeheoemaaaaaaacaaaaaaaiaaaaaadiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaaebaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaafaepfdejfeejepeoaafeeffiedepepfceeaaklkl
epfdeheogiaaaaaaadaaaaaaaiaaaaaafaaaaaaaaaaaaaaaabaaaaaaadaaaaaa
aaaaaaaaapaaaaaafmaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaapaaaaaa
fmaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaaadamaaaafdfgfpfaepfdejfe
ejepeoaafeeffiedepepfceeaaklklklfdeieefcleabaaaaeaaaabaagnaaaaaa
fjaaaaaeegiocaaaaaaaaaaaaiaaaaaafjaaaaaeegiocaaaabaaaaaaaeaaaaaa
fpaaaaadpcbabaaaaaaaaaaafpaaaaaddcbabaaaabaaaaaaghaaaaaepccabaaa
aaaaaaaaabaaaaaagfaaaaadpccabaaaabaaaaaagfaaaaaddccabaaaacaaaaaa
giaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaaegiocaaa
abaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaaaaaaaaa
agbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpccabaaa
aaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaaaaaaaaaa
dgaaaaafdccabaaaabaaaaaaegbabaaaabaaaaaadgaaaaaimccabaaaabaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaiadpaaaaiadpdgaaaaagjcaabaaaaaaaaaaa
agiacaaaaaaaaaaaahaaaaaadgaaaaaigcaabaaaaaaaaaaaaceaaaaaaaaaaaaa
aaaaiadpaaaaaaaaaaaaaaaadiaaaaaidcaabaaaaaaaaaaaegaabaaaaaaaaaaa
egiacaaaaaaaaaaaagaaaaaadiaaaaahdccabaaaacaaaaaaogakbaaaaaaaaaaa
egaabaaaaaaaaaaadoaaaaab"
}
SubProgram "d3d11_9x " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 160
Vector 96 [_MainTex_TexelSize]
Vector 112 [_Parameter]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0_level_9_1
eefiecedpfommaickciflkhoaifmebmeehicibnkabaaaaaapmadaaaaaeaaaaaa
daaaaaaahmabaaaadiadaaaaimadaaaaebgpgodjeeabaaaaeeabaaaaaaacpopp
aeabaaaaeaaaaaaaacaaceaaaaaadmaaaaaadmaaaaaaceaaabaadmaaaaaaagaa
acaaabaaaaaaaaaaabaaaaaaaeaaadaaaaaaaaaaaaaaaaaaaaacpoppfbaaaaaf
ahaaapkaaaaaiadpaaaaaaaaaaaaaaaaaaaaaaaabpaaaaacafaaaaiaaaaaapja
bpaaaaacafaaabiaabaaapjaabaaaaacaaaaadiaahaaoekaafaaaaadaaaaapia
aaaabeiaacaaaakaacaaaaadaaaaadiaaaaaoeiaahaaobkaafaaaaadaaaaadia
aaaaoeiaabaaoekaafaaaaadabaaadoaaaaaooiaaaaaoeiaafaaaaadaaaaapia
aaaaffjaaeaaoekaaeaaaaaeaaaaapiaadaaoekaaaaaaajaaaaaoeiaaeaaaaae
aaaaapiaafaaoekaaaaakkjaaaaaoeiaaeaaaaaeaaaaapiaagaaoekaaaaappja
aaaaoeiaaeaaaaaeaaaaadmaaaaappiaaaaaoekaaaaaoeiaabaaaaacaaaaamma
aaaaoeiaaeaaaaaeaaaaapoaabaaaejaahaafakaahaaafkappppaaaafdeieefc
leabaaaaeaaaabaagnaaaaaafjaaaaaeegiocaaaaaaaaaaaaiaaaaaafjaaaaae
egiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaaddcbabaaa
abaaaaaaghaaaaaepccabaaaaaaaaaaaabaaaaaagfaaaaadpccabaaaabaaaaaa
gfaaaaaddccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaa
fgbfbaaaaaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaa
egiocaaaabaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaak
pcaabaaaaaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaa
aaaaaaaadcaaaaakpccabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaa
aaaaaaaaegaobaaaaaaaaaaadgaaaaafdccabaaaabaaaaaaegbabaaaabaaaaaa
dgaaaaaimccabaaaabaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaiadpaaaaiadp
dgaaaaagjcaabaaaaaaaaaaaagiacaaaaaaaaaaaahaaaaaadgaaaaaigcaabaaa
aaaaaaaaaceaaaaaaaaaaaaaaaaaiadpaaaaaaaaaaaaaaaadiaaaaaidcaabaaa
aaaaaaaaegaabaaaaaaaaaaaegiacaaaaaaaaaaaagaaaaaadiaaaaahdccabaaa
acaaaaaaogakbaaaaaaaaaaaegaabaaaaaaaaaaadoaaaaabejfdeheoemaaaaaa
acaaaaaaaiaaaaaadiaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaa
ebaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadadaaaafaepfdejfeejepeo
aafeeffiedepepfceeaaklklepfdeheogiaaaaaaadaaaaaaaiaaaaaafaaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaafmaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaafmaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
adamaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaklklkl"
}
}
Program "fp" {
SubProgram "opengl " {
"!!GLSL"
}
SubProgram "d3d9 " {
SetTexture 0 [_MainTex] 2D 0
"ps_2_0
def c0, 0.0205000006, 0.0205000006, 0.0205000006, 0
def c1, 0.0855000019, 0.0855000019, 0.0855000019, 0
def c2, 0.231999993, 0.231999993, 0.231999993, 0
def c3, 0.324000001, 0.324000001, 0.324000001, 1
def c4, 3, 0, 0, 0
dcl_pp t0.xy
dcl_pp t1.xy
dcl_2d s0
mov r0.xy, t1
mad_pp r0.xy, r0, -c4.x, t0
add_pp r1.xy, r0, t1
add_pp r2.xy, r1, t1
add_pp r3.xy, r2, t1
add_pp r4.xy, r3, t1
add_pp r5.xy, r4, t1
add_pp r6.xy, r5, t1
texld_pp r0, r0, s0
texld_pp r1, r1, s0
texld_pp r2, r2, s0
texld_pp r3, r3, s0
texld_pp r4, r4, s0
texld_pp r5, r5, s0
texld_pp r6, r6, s0
mul_pp r1, r1, c1
mad_pp r0, r0, c0, r1
mad_pp r0, r2, c2, r0
mad_pp r0, r3, c3, r0
mad_pp r0, r4, c2, r0
mad_pp r0, r5, c1, r0
mad_pp r0, r6, c0, r0
mov_pp oC0, r0

"
}
SubProgram "d3d11 " {
SetTexture 0 [_MainTex] 2D 0
"ps_4_0
eefiecedpmidpnaopnhhgdlplnhdohjapolhdokbabaaaaaaoiacaaaaadaaaaaa
cmaaaaaajmaaaaaanaaaaaaaejfdeheogiaaaaaaadaaaaaaaiaaaaaafaaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaafmaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapadaaaafmaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
adadaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaklklklepfdeheo
cmaaaaaaabaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaa
apaaaaaafdfgfpfegbhcghgfheaaklklfdeieefcbaacaaaaeaaaaaaaieaaaaaa
dfbiaaaaboaaaaaajoopkhdmaaaaaaaaaaaaaaaaaaaaaaaakabkkpdnaaaaaaaa
aaaaaaaaaaaaaaaagijbgndoaaaaaaaaaaaaaaaaaaaaaaaafeodkfdoaaaaaaaa
aaaaaaaaaaaaiadpgijbgndoaaaaaaaaaaaaaaaaaaaaaaaakabkkpdnaaaaaaaa
aaaaaaaaaaaaaaaajoopkhdmaaaaaaaaaaaaaaaaaaaaaaaafkaaaaadaagabaaa
aaaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaagcbaaaaddcbabaaaabaaaaaa
gcbaaaaddcbabaaaacaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaacaeaaaaaa
dcaaaaandcaabaaaaaaaaaaaegbabaiaebaaaaaaacaaaaaaaceaaaaaaaaaeaea
aaaaeaeaaaaaaaaaaaaaaaaaegbabaaaabaaaaaadgaaaaaipcaabaaaabaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadgaaaaafmcaabaaaaaaaaaaa
agaebaaaaaaaaaaadgaaaaafbcaabaaaacaaaaaaabeaaaaaaaaaaaaadaaaaaab
cbaaaaahccaabaaaacaaaaaaakaabaaaacaaaaaaabeaaaaaahaaaaaaadaaaead
bkaabaaaacaaaaaaefaaaaajpcaabaaaadaaaaaaogakbaaaaaaaaaaaeghobaaa
aaaaaaaaaagabaaaaaaaaaaadcaaaaakpcaabaaaabaaaaaaegaobaaaadaaaaaa
agjmjaaaakaabaaaacaaaaaaegaobaaaabaaaaaaaaaaaaahmcaabaaaaaaaaaaa
kgaobaaaaaaaaaaaagbebaaaacaaaaaaboaaaaahbcaabaaaacaaaaaaakaabaaa
acaaaaaaabeaaaaaabaaaaaabgaaaaabdgaaaaafpccabaaaaaaaaaaaegaobaaa
abaaaaaadoaaaaab"
}
SubProgram "d3d11_9x " {
SetTexture 0 [_MainTex] 2D 0
"ps_4_0_level_9_1
eefiecedkefjebgeooefdcphfdeaiiolpogjdobnabaaaaaaeeafaaaaaeaaaaaa
daaaaaaaiiacaaaakaaeaaaabaafaaaaebgpgodjfaacaaaafaacaaaaaaacpppp
ciacaaaaciaaaaaaaaaaciaaaaaaciaaaaaaciaaabaaceaaaaaaciaaaaaaaaaa
aaacppppfbaaaaafaaaaapkajoopkhdmjoopkhdmjoopkhdmaaaaaaaafbaaaaaf
abaaapkakabkkpdnkabkkpdnkabkkpdnaaaaaaaafbaaaaafacaaapkafeodkfdo
feodkfdofeodkfdoaaaaiadpfbaaaaafadaaapkagijbgndogijbgndogijbgndo
aaaaaaaafbaaaaafaeaaapkaaaaaeaeaaaaaaaaaaaaaaaaaaaaaaaaabpaaaaac
aaaaaaiaaaaacplabpaaaaacaaaaaaiaabaacdlabpaaaaacaaaaaajaaaaiapka
abaaaaacaaaaadiaabaaoelaaeaaaaaeaaaacdiaaaaaoeiaaeaaaakbaaaaoela
acaaaaadabaacdiaaaaaoeiaabaaoelaacaaaaadacaacdiaabaaoeiaabaaoela
acaaaaadadaacdiaacaaoeiaabaaoelaacaaaaadaeaacdiaadaaoeiaabaaoela
acaaaaadafaacdiaaeaaoeiaabaaoelaacaaaaadagaacdiaafaaoeiaabaaoela
ecaaaaadaaaacpiaaaaaoeiaaaaioekaecaaaaadabaacpiaabaaoeiaaaaioeka
ecaaaaadacaacpiaacaaoeiaaaaioekaecaaaaadadaacpiaadaaoeiaaaaioeka
ecaaaaadaeaacpiaaeaaoeiaaaaioekaecaaaaadafaacpiaafaaoeiaaaaioeka
ecaaaaadagaacpiaagaaoeiaaaaioekaafaaaaadabaacpiaabaaoeiaabaaoeka
aeaaaaaeaaaacpiaaaaaoeiaaaaaoekaabaaoeiaaeaaaaaeaaaacpiaacaaoeia
adaaoekaaaaaoeiaaeaaaaaeaaaacpiaadaaoeiaacaaoekaaaaaoeiaaeaaaaae
aaaacpiaaeaaoeiaadaaoekaaaaaoeiaaeaaaaaeaaaacpiaafaaoeiaabaaoeka
aaaaoeiaaeaaaaaeaaaacpiaagaaoeiaaaaaoekaaaaaoeiaabaaaaacaaaicpia
aaaaoeiappppaaaafdeieefcbaacaaaaeaaaaaaaieaaaaaadfbiaaaaboaaaaaa
joopkhdmaaaaaaaaaaaaaaaaaaaaaaaakabkkpdnaaaaaaaaaaaaaaaaaaaaaaaa
gijbgndoaaaaaaaaaaaaaaaaaaaaaaaafeodkfdoaaaaaaaaaaaaaaaaaaaaiadp
gijbgndoaaaaaaaaaaaaaaaaaaaaaaaakabkkpdnaaaaaaaaaaaaaaaaaaaaaaaa
joopkhdmaaaaaaaaaaaaaaaaaaaaaaaafkaaaaadaagabaaaaaaaaaaafibiaaae
aahabaaaaaaaaaaaffffaaaagcbaaaaddcbabaaaabaaaaaagcbaaaaddcbabaaa
acaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaacaeaaaaaadcaaaaandcaabaaa
aaaaaaaaegbabaiaebaaaaaaacaaaaaaaceaaaaaaaaaeaeaaaaaeaeaaaaaaaaa
aaaaaaaaegbabaaaabaaaaaadgaaaaaipcaabaaaabaaaaaaaceaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaadgaaaaafmcaabaaaaaaaaaaaagaebaaaaaaaaaaa
dgaaaaafbcaabaaaacaaaaaaabeaaaaaaaaaaaaadaaaaaabcbaaaaahccaabaaa
acaaaaaaakaabaaaacaaaaaaabeaaaaaahaaaaaaadaaaeadbkaabaaaacaaaaaa
efaaaaajpcaabaaaadaaaaaaogakbaaaaaaaaaaaeghobaaaaaaaaaaaaagabaaa
aaaaaaaadcaaaaakpcaabaaaabaaaaaaegaobaaaadaaaaaaagjmjaaaakaabaaa
acaaaaaaegaobaaaabaaaaaaaaaaaaahmcaabaaaaaaaaaaakgaobaaaaaaaaaaa
agbebaaaacaaaaaaboaaaaahbcaabaaaacaaaaaaakaabaaaacaaaaaaabeaaaaa
abaaaaaabgaaaaabdgaaaaafpccabaaaaaaaaaaaegaobaaaabaaaaaadoaaaaab
ejfdeheogiaaaaaaadaaaaaaaiaaaaaafaaaaaaaaaaaaaaaabaaaaaaadaaaaaa
aaaaaaaaapaaaaaafmaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaapadaaaa
fmaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaaadadaaaafdfgfpfaepfdejfe
ejepeoaafeeffiedepepfceeaaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaa
caaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgf
heaaklkl"
}
}
 }
 Pass {
  ZTest Always
  ZWrite Off
  Cull Off
  Fog { Mode Off }
  GpuProgramID 235782
Program "vp" {
SubProgram "opengl " {
"!!GLSL
#ifdef VERTEX

uniform vec4 _MainTex_TexelSize;
uniform vec4 _Parameter;
varying vec4 xlv_TEXCOORD0;
varying vec2 xlv_TEXCOORD1;
void main ()
{
  vec4 tmpvar_1;
  tmpvar_1.zw = vec2(1.0, 1.0);
  tmpvar_1.xy = gl_MultiTexCoord0.xy;
  gl_Position = (gl_ModelViewProjectionMatrix * gl_Vertex);
  xlv_TEXCOORD0 = tmpvar_1;
  xlv_TEXCOORD1 = ((_MainTex_TexelSize.xy * vec2(1.0, 0.0)) * _Parameter.x);
}


#endif
#ifdef FRAGMENT
uniform sampler2D _MainTex;
varying vec4 xlv_TEXCOORD0;
varying vec2 xlv_TEXCOORD1;
void main ()
{
  vec4 color_1;
  vec2 coords_2;
  coords_2 = (xlv_TEXCOORD0.xy - (xlv_TEXCOORD1 * 3.0));
  color_1 = (texture2D (_MainTex, coords_2) * vec4(0.0205, 0.0205, 0.0205, 0.0));
  coords_2 = (coords_2 + xlv_TEXCOORD1);
  color_1 = (color_1 + (texture2D (_MainTex, coords_2) * vec4(0.0855, 0.0855, 0.0855, 0.0)));
  coords_2 = (coords_2 + xlv_TEXCOORD1);
  color_1 = (color_1 + (texture2D (_MainTex, coords_2) * vec4(0.232, 0.232, 0.232, 0.0)));
  coords_2 = (coords_2 + xlv_TEXCOORD1);
  color_1 = (color_1 + (texture2D (_MainTex, coords_2) * vec4(0.324, 0.324, 0.324, 1.0)));
  coords_2 = (coords_2 + xlv_TEXCOORD1);
  color_1 = (color_1 + (texture2D (_MainTex, coords_2) * vec4(0.232, 0.232, 0.232, 0.0)));
  coords_2 = (coords_2 + xlv_TEXCOORD1);
  color_1 = (color_1 + (texture2D (_MainTex, coords_2) * vec4(0.0855, 0.0855, 0.0855, 0.0)));
  coords_2 = (coords_2 + xlv_TEXCOORD1);
  color_1 = (color_1 + (texture2D (_MainTex, coords_2) * vec4(0.0205, 0.0205, 0.0205, 0.0)));
  coords_2 = (coords_2 + xlv_TEXCOORD1);
  gl_FragData[0] = color_1;
}


#endif
"
}
SubProgram "d3d9 " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
Matrix 0 [glstate_matrix_mvp]
Vector 4 [_MainTex_TexelSize]
Vector 5 [_Parameter]
"vs_2_0
def c6, 0, 1, 0, 0
dcl_position v0
dcl_texcoord v1
dp4 oPos.x, c0, v0
dp4 oPos.y, c1, v0
dp4 oPos.z, c2, v0
dp4 oPos.w, c3, v0
mov r0.xy, c6
mul r0, r0.xyyx, c5.x
add r0.xy, r0, c6.yxzw
mul r0.xy, r0, c4
mul oT1.xy, r0.zwzw, r0
mad oT0, v1.xyxx, c6.yyxx, c6.xxyy

"
}
SubProgram "d3d11 " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 160
Vector 96 [_MainTex_TexelSize]
Vector 112 [_Parameter]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedljhpkihbnjagaennnfdgfaojdemhdnepabaaaaaakmacaaaaadaaaaaa
cmaaaaaaiaaaaaaapaaaaaaaejfdeheoemaaaaaaacaaaaaaaiaaaaaadiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaaebaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaafaepfdejfeejepeoaafeeffiedepepfceeaaklkl
epfdeheogiaaaaaaadaaaaaaaiaaaaaafaaaaaaaaaaaaaaaabaaaaaaadaaaaaa
aaaaaaaaapaaaaaafmaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaapaaaaaa
fmaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaaadamaaaafdfgfpfaepfdejfe
ejepeoaafeeffiedepepfceeaaklklklfdeieefcleabaaaaeaaaabaagnaaaaaa
fjaaaaaeegiocaaaaaaaaaaaaiaaaaaafjaaaaaeegiocaaaabaaaaaaaeaaaaaa
fpaaaaadpcbabaaaaaaaaaaafpaaaaaddcbabaaaabaaaaaaghaaaaaepccabaaa
aaaaaaaaabaaaaaagfaaaaadpccabaaaabaaaaaagfaaaaaddccabaaaacaaaaaa
giaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaaegiocaaa
abaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaaaaaaaaa
agbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpccabaaa
aaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaaaaaaaaaa
dgaaaaafdccabaaaabaaaaaaegbabaaaabaaaaaadgaaaaaimccabaaaabaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaiadpaaaaiadpdgaaaaaijcaabaaaaaaaaaaa
aceaaaaaaaaaiadpaaaaaaaaaaaaaaaaaaaaaaaadgaaaaaggcaabaaaaaaaaaaa
agiacaaaaaaaaaaaahaaaaaadiaaaaaidcaabaaaaaaaaaaaegaabaaaaaaaaaaa
egiacaaaaaaaaaaaagaaaaaadiaaaaahdccabaaaacaaaaaaogakbaaaaaaaaaaa
egaabaaaaaaaaaaadoaaaaab"
}
SubProgram "d3d11_9x " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 160
Vector 96 [_MainTex_TexelSize]
Vector 112 [_Parameter]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0_level_9_1
eefiecedjdoalgpnlfbajojgndmhkkinnongmpjcabaaaaaapmadaaaaaeaaaaaa
daaaaaaahmabaaaadiadaaaaimadaaaaebgpgodjeeabaaaaeeabaaaaaaacpopp
aeabaaaaeaaaaaaaacaaceaaaaaadmaaaaaadmaaaaaaceaaabaadmaaaaaaagaa
acaaabaaaaaaaaaaabaaaaaaaeaaadaaaaaaaaaaaaaaaaaaaaacpoppfbaaaaaf
ahaaapkaaaaaaaaaaaaaiadpaaaaaaaaaaaaaaaabpaaaaacafaaaaiaaaaaapja
bpaaaaacafaaabiaabaaapjaabaaaaacaaaaadiaahaaoekaafaaaaadaaaaapia
aaaabeiaacaaaakaacaaaaadaaaaadiaaaaaoeiaahaaobkaafaaaaadaaaaadia
aaaaoeiaabaaoekaafaaaaadabaaadoaaaaaooiaaaaaoeiaafaaaaadaaaaapia
aaaaffjaaeaaoekaaeaaaaaeaaaaapiaadaaoekaaaaaaajaaaaaoeiaaeaaaaae
aaaaapiaafaaoekaaaaakkjaaaaaoeiaaeaaaaaeaaaaapiaagaaoekaaaaappja
aaaaoeiaaeaaaaaeaaaaadmaaaaappiaaaaaoekaaaaaoeiaabaaaaacaaaaamma
aaaaoeiaaeaaaaaeaaaaapoaabaaaejaahaaafkaahaafakappppaaaafdeieefc
leabaaaaeaaaabaagnaaaaaafjaaaaaeegiocaaaaaaaaaaaaiaaaaaafjaaaaae
egiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaaddcbabaaa
abaaaaaaghaaaaaepccabaaaaaaaaaaaabaaaaaagfaaaaadpccabaaaabaaaaaa
gfaaaaaddccabaaaacaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaa
fgbfbaaaaaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaa
egiocaaaabaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaak
pcaabaaaaaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaa
aaaaaaaadcaaaaakpccabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaa
aaaaaaaaegaobaaaaaaaaaaadgaaaaafdccabaaaabaaaaaaegbabaaaabaaaaaa
dgaaaaaimccabaaaabaaaaaaaceaaaaaaaaaaaaaaaaaaaaaaaaaiadpaaaaiadp
dgaaaaaijcaabaaaaaaaaaaaaceaaaaaaaaaiadpaaaaaaaaaaaaaaaaaaaaaaaa
dgaaaaaggcaabaaaaaaaaaaaagiacaaaaaaaaaaaahaaaaaadiaaaaaidcaabaaa
aaaaaaaaegaabaaaaaaaaaaaegiacaaaaaaaaaaaagaaaaaadiaaaaahdccabaaa
acaaaaaaogakbaaaaaaaaaaaegaabaaaaaaaaaaadoaaaaabejfdeheoemaaaaaa
acaaaaaaaiaaaaaadiaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaa
ebaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadadaaaafaepfdejfeejepeo
aafeeffiedepepfceeaaklklepfdeheogiaaaaaaadaaaaaaaiaaaaaafaaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaafmaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaafmaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
adamaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaklklkl"
}
}
Program "fp" {
SubProgram "opengl " {
"!!GLSL"
}
SubProgram "d3d9 " {
SetTexture 0 [_MainTex] 2D 0
"ps_2_0
def c0, 0.0205000006, 0.0205000006, 0.0205000006, 0
def c1, 0.0855000019, 0.0855000019, 0.0855000019, 0
def c2, 0.231999993, 0.231999993, 0.231999993, 0
def c3, 0.324000001, 0.324000001, 0.324000001, 1
def c4, 3, 0, 0, 0
dcl_pp t0.xy
dcl_pp t1.xy
dcl_2d s0
mov r0.xy, t1
mad_pp r0.xy, r0, -c4.x, t0
add_pp r1.xy, r0, t1
add_pp r2.xy, r1, t1
add_pp r3.xy, r2, t1
add_pp r4.xy, r3, t1
add_pp r5.xy, r4, t1
add_pp r6.xy, r5, t1
texld_pp r0, r0, s0
texld_pp r1, r1, s0
texld_pp r2, r2, s0
texld_pp r3, r3, s0
texld_pp r4, r4, s0
texld_pp r5, r5, s0
texld_pp r6, r6, s0
mul_pp r1, r1, c1
mad_pp r0, r0, c0, r1
mad_pp r0, r2, c2, r0
mad_pp r0, r3, c3, r0
mad_pp r0, r4, c2, r0
mad_pp r0, r5, c1, r0
mad_pp r0, r6, c0, r0
mov_pp oC0, r0

"
}
SubProgram "d3d11 " {
SetTexture 0 [_MainTex] 2D 0
"ps_4_0
eefiecedpmidpnaopnhhgdlplnhdohjapolhdokbabaaaaaaoiacaaaaadaaaaaa
cmaaaaaajmaaaaaanaaaaaaaejfdeheogiaaaaaaadaaaaaaaiaaaaaafaaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaafmaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapadaaaafmaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
adadaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaklklklepfdeheo
cmaaaaaaabaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaa
apaaaaaafdfgfpfegbhcghgfheaaklklfdeieefcbaacaaaaeaaaaaaaieaaaaaa
dfbiaaaaboaaaaaajoopkhdmaaaaaaaaaaaaaaaaaaaaaaaakabkkpdnaaaaaaaa
aaaaaaaaaaaaaaaagijbgndoaaaaaaaaaaaaaaaaaaaaaaaafeodkfdoaaaaaaaa
aaaaaaaaaaaaiadpgijbgndoaaaaaaaaaaaaaaaaaaaaaaaakabkkpdnaaaaaaaa
aaaaaaaaaaaaaaaajoopkhdmaaaaaaaaaaaaaaaaaaaaaaaafkaaaaadaagabaaa
aaaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaagcbaaaaddcbabaaaabaaaaaa
gcbaaaaddcbabaaaacaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaacaeaaaaaa
dcaaaaandcaabaaaaaaaaaaaegbabaiaebaaaaaaacaaaaaaaceaaaaaaaaaeaea
aaaaeaeaaaaaaaaaaaaaaaaaegbabaaaabaaaaaadgaaaaaipcaabaaaabaaaaaa
aceaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadgaaaaafmcaabaaaaaaaaaaa
agaebaaaaaaaaaaadgaaaaafbcaabaaaacaaaaaaabeaaaaaaaaaaaaadaaaaaab
cbaaaaahccaabaaaacaaaaaaakaabaaaacaaaaaaabeaaaaaahaaaaaaadaaaead
bkaabaaaacaaaaaaefaaaaajpcaabaaaadaaaaaaogakbaaaaaaaaaaaeghobaaa
aaaaaaaaaagabaaaaaaaaaaadcaaaaakpcaabaaaabaaaaaaegaobaaaadaaaaaa
agjmjaaaakaabaaaacaaaaaaegaobaaaabaaaaaaaaaaaaahmcaabaaaaaaaaaaa
kgaobaaaaaaaaaaaagbebaaaacaaaaaaboaaaaahbcaabaaaacaaaaaaakaabaaa
acaaaaaaabeaaaaaabaaaaaabgaaaaabdgaaaaafpccabaaaaaaaaaaaegaobaaa
abaaaaaadoaaaaab"
}
SubProgram "d3d11_9x " {
SetTexture 0 [_MainTex] 2D 0
"ps_4_0_level_9_1
eefiecedkefjebgeooefdcphfdeaiiolpogjdobnabaaaaaaeeafaaaaaeaaaaaa
daaaaaaaiiacaaaakaaeaaaabaafaaaaebgpgodjfaacaaaafaacaaaaaaacpppp
ciacaaaaciaaaaaaaaaaciaaaaaaciaaaaaaciaaabaaceaaaaaaciaaaaaaaaaa
aaacppppfbaaaaafaaaaapkajoopkhdmjoopkhdmjoopkhdmaaaaaaaafbaaaaaf
abaaapkakabkkpdnkabkkpdnkabkkpdnaaaaaaaafbaaaaafacaaapkafeodkfdo
feodkfdofeodkfdoaaaaiadpfbaaaaafadaaapkagijbgndogijbgndogijbgndo
aaaaaaaafbaaaaafaeaaapkaaaaaeaeaaaaaaaaaaaaaaaaaaaaaaaaabpaaaaac
aaaaaaiaaaaacplabpaaaaacaaaaaaiaabaacdlabpaaaaacaaaaaajaaaaiapka
abaaaaacaaaaadiaabaaoelaaeaaaaaeaaaacdiaaaaaoeiaaeaaaakbaaaaoela
acaaaaadabaacdiaaaaaoeiaabaaoelaacaaaaadacaacdiaabaaoeiaabaaoela
acaaaaadadaacdiaacaaoeiaabaaoelaacaaaaadaeaacdiaadaaoeiaabaaoela
acaaaaadafaacdiaaeaaoeiaabaaoelaacaaaaadagaacdiaafaaoeiaabaaoela
ecaaaaadaaaacpiaaaaaoeiaaaaioekaecaaaaadabaacpiaabaaoeiaaaaioeka
ecaaaaadacaacpiaacaaoeiaaaaioekaecaaaaadadaacpiaadaaoeiaaaaioeka
ecaaaaadaeaacpiaaeaaoeiaaaaioekaecaaaaadafaacpiaafaaoeiaaaaioeka
ecaaaaadagaacpiaagaaoeiaaaaioekaafaaaaadabaacpiaabaaoeiaabaaoeka
aeaaaaaeaaaacpiaaaaaoeiaaaaaoekaabaaoeiaaeaaaaaeaaaacpiaacaaoeia
adaaoekaaaaaoeiaaeaaaaaeaaaacpiaadaaoeiaacaaoekaaaaaoeiaaeaaaaae
aaaacpiaaeaaoeiaadaaoekaaaaaoeiaaeaaaaaeaaaacpiaafaaoeiaabaaoeka
aaaaoeiaaeaaaaaeaaaacpiaagaaoeiaaaaaoekaaaaaoeiaabaaaaacaaaicpia
aaaaoeiappppaaaafdeieefcbaacaaaaeaaaaaaaieaaaaaadfbiaaaaboaaaaaa
joopkhdmaaaaaaaaaaaaaaaaaaaaaaaakabkkpdnaaaaaaaaaaaaaaaaaaaaaaaa
gijbgndoaaaaaaaaaaaaaaaaaaaaaaaafeodkfdoaaaaaaaaaaaaaaaaaaaaiadp
gijbgndoaaaaaaaaaaaaaaaaaaaaaaaakabkkpdnaaaaaaaaaaaaaaaaaaaaaaaa
joopkhdmaaaaaaaaaaaaaaaaaaaaaaaafkaaaaadaagabaaaaaaaaaaafibiaaae
aahabaaaaaaaaaaaffffaaaagcbaaaaddcbabaaaabaaaaaagcbaaaaddcbabaaa
acaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaacaeaaaaaadcaaaaandcaabaaa
aaaaaaaaegbabaiaebaaaaaaacaaaaaaaceaaaaaaaaaeaeaaaaaeaeaaaaaaaaa
aaaaaaaaegbabaaaabaaaaaadgaaaaaipcaabaaaabaaaaaaaceaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaadgaaaaafmcaabaaaaaaaaaaaagaebaaaaaaaaaaa
dgaaaaafbcaabaaaacaaaaaaabeaaaaaaaaaaaaadaaaaaabcbaaaaahccaabaaa
acaaaaaaakaabaaaacaaaaaaabeaaaaaahaaaaaaadaaaeadbkaabaaaacaaaaaa
efaaaaajpcaabaaaadaaaaaaogakbaaaaaaaaaaaeghobaaaaaaaaaaaaagabaaa
aaaaaaaadcaaaaakpcaabaaaabaaaaaaegaobaaaadaaaaaaagjmjaaaakaabaaa
acaaaaaaegaobaaaabaaaaaaaaaaaaahmcaabaaaaaaaaaaakgaobaaaaaaaaaaa
agbebaaaacaaaaaaboaaaaahbcaabaaaacaaaaaaakaabaaaacaaaaaaabeaaaaa
abaaaaaabgaaaaabdgaaaaafpccabaaaaaaaaaaaegaobaaaabaaaaaadoaaaaab
ejfdeheogiaaaaaaadaaaaaaaiaaaaaafaaaaaaaaaaaaaaaabaaaaaaadaaaaaa
aaaaaaaaapaaaaaafmaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaapadaaaa
fmaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaaadadaaaafdfgfpfaepfdejfe
ejepeoaafeeffiedepepfceeaaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaa
caaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgf
heaaklkl"
}
}
 }
 Pass {
  ZTest Always
  ZWrite Off
  Cull Off
  Fog { Mode Off }
  GpuProgramID 262395
Program "vp" {
SubProgram "opengl " {
"!!GLSL
#ifdef VERTEX

uniform vec4 _MainTex_TexelSize;
uniform vec4 _Parameter;
varying vec2 xlv_TEXCOORD0;
varying vec4 xlv_TEXCOORD1;
varying vec4 xlv_TEXCOORD1_1;
varying vec4 xlv_TEXCOORD1_2;
void main ()
{
  vec4 tmpvar_1;
  tmpvar_1.zw = vec2(1.0, 1.0);
  tmpvar_1.xy = gl_MultiTexCoord0.xy;
  vec2 tmpvar_2;
  tmpvar_2 = ((_MainTex_TexelSize.xy * vec2(0.0, 1.0)) * _Parameter.x);
  vec4 tmpvar_3;
  tmpvar_3 = (-(tmpvar_2.xyxy) * 3.0);
  vec4 tmpvar_4;
  tmpvar_4 = (tmpvar_3 + tmpvar_2.xyxy);
  gl_Position = (gl_ModelViewProjectionMatrix * gl_Vertex);
  xlv_TEXCOORD0 = tmpvar_1.xy;
  xlv_TEXCOORD1 = (gl_MultiTexCoord0.xyxy + (tmpvar_3 * vec4(1.0, 1.0, -1.0, -1.0)));
  xlv_TEXCOORD1_1 = (gl_MultiTexCoord0.xyxy + (tmpvar_4 * vec4(1.0, 1.0, -1.0, -1.0)));
  xlv_TEXCOORD1_2 = (gl_MultiTexCoord0.xyxy + ((tmpvar_4 + tmpvar_2.xyxy) * vec4(1.0, 1.0, -1.0, -1.0)));
}


#endif
#ifdef FRAGMENT
uniform sampler2D _MainTex;
varying vec2 xlv_TEXCOORD0;
varying vec4 xlv_TEXCOORD1;
varying vec4 xlv_TEXCOORD1_1;
varying vec4 xlv_TEXCOORD1_2;
void main ()
{
  vec4 color_1;
  color_1 = (texture2D (_MainTex, xlv_TEXCOORD0) * vec4(0.324, 0.324, 0.324, 1.0));
  color_1 = (color_1 + ((texture2D (_MainTex, xlv_TEXCOORD1.xy) + texture2D (_MainTex, xlv_TEXCOORD1.zw)) * vec4(0.0205, 0.0205, 0.0205, 0.0)));
  color_1 = (color_1 + ((texture2D (_MainTex, xlv_TEXCOORD1_1.xy) + texture2D (_MainTex, xlv_TEXCOORD1_1.zw)) * vec4(0.0855, 0.0855, 0.0855, 0.0)));
  color_1 = (color_1 + ((texture2D (_MainTex, xlv_TEXCOORD1_2.xy) + texture2D (_MainTex, xlv_TEXCOORD1_2.zw)) * vec4(0.232, 0.232, 0.232, 0.0)));
  gl_FragData[0] = color_1;
}


#endif
"
}
SubProgram "d3d9 " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
Matrix 0 [glstate_matrix_mvp]
Vector 4 [_MainTex_TexelSize]
Vector 5 [_Parameter]
"vs_2_0
def c6, 1, 0, -1, -0
def c7, 0, -2, -0, 2
def c8, -0, -3, 0, 3
dcl_position v0
dcl_texcoord v1
dp4 oPos.x, c0, v0
dp4 oPos.y, c1, v0
dp4 oPos.z, c2, v0
dp4 oPos.w, c3, v0
mov r0.xy, c6
mad r0.xy, c5.x, r0, r0.yxzw
mul r0.xy, r0, c4
mul r0.z, r0.y, c5.x
mad oT1, r0.xzxz, c8, v1.xyxy
mad oT2, r0.xzxz, c7, v1.xyxy
mad oT3, r0.xzxz, c6.yzwx, v1.xyxy
mov oT0.xy, v1

"
}
SubProgram "d3d11 " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 160
Vector 96 [_MainTex_TexelSize]
Vector 112 [_Parameter]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedpkcphpjefjojfacmkeljhdfleleicjogabaaaaaafmadaaaaadaaaaaa
cmaaaaaaiaaaaaaacaabaaaaejfdeheoemaaaaaaacaaaaaaaiaaaaaadiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaaebaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaafaepfdejfeejepeoaafeeffiedepepfceeaaklkl
epfdeheojiaaaaaaafaaaaaaaiaaaaaaiaaaaaaaaaaaaaaaabaaaaaaadaaaaaa
aaaaaaaaapaaaaaaimaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaa
imaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaaapaaaaaaimaaaaaaacaaaaaa
aaaaaaaaadaaaaaaadaaaaaaapaaaaaaimaaaaaaadaaaaaaaaaaaaaaadaaaaaa
aeaaaaaaapaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaklklkl
fdeieefcdeacaaaaeaaaabaainaaaaaafjaaaaaeegiocaaaaaaaaaaaaiaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaabaaaaaaghaaaaaepccabaaaaaaaaaaaabaaaaaagfaaaaaddccabaaa
abaaaaaagfaaaaadpccabaaaacaaaaaagfaaaaadpccabaaaadaaaaaagfaaaaad
pccabaaaaeaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpccabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafdccabaaaabaaaaaaegbabaaaabaaaaaadgaaaaag
bcaabaaaaaaaaaaaakiacaaaaaaaaaaaahaaaaaadgaaaaafccaabaaaaaaaaaaa
abeaaaaaaaaaiadpdiaaaaaidcaabaaaaaaaaaaaegaabaaaaaaaaaaaegiacaaa
aaaaaaaaagaaaaaadiaaaaaiecaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaaa
aaaaaaaaahaaaaaadcaaaaampccabaaaacaaaaaaigaibaaaaaaaaaaaaceaaaaa
aaaaaaiaaaaaeamaaaaaaaaaaaaaeaeaegbebaaaabaaaaaadcaaaaampccabaaa
adaaaaaaigaibaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaaamaaaaaaaiaaaaaaaea
egbebaaaabaaaaaadcaaaaampccabaaaaeaaaaaaigaibaaaaaaaaaaaaceaaaaa
aaaaaaaaaaaaialpaaaaaaiaaaaaiadpegbebaaaabaaaaaadoaaaaab"
}
SubProgram "d3d11_9x " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 160
Vector 96 [_MainTex_TexelSize]
Vector 112 [_Parameter]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0_level_9_1
eefiecedkkkdedohhlcldpdndmlgbkpjnmijpcodabaaaaaaaeafaaaaaeaaaaaa
daaaaaaaneabaaaabaaeaaaageaeaaaaebgpgodjjmabaaaajmabaaaaaaacpopp
fmabaaaaeaaaaaaaacaaceaaaaaadmaaaaaadmaaaaaaceaaabaadmaaaaaaagaa
acaaabaaaaaaaaaaabaaaaaaaeaaadaaaaaaaaaaaaaaaaaaaaacpoppfbaaaaaf
ahaaapkaaaaaiadpaaaaaaaaaaaaialpaaaaaaiafbaaaaafaiaaapkaaaaaaaaa
aaaaaamaaaaaaaiaaaaaaaeafbaaaaafajaaapkaaaaaaaiaaaaaeamaaaaaaaaa
aaaaeaeabpaaaaacafaaaaiaaaaaapjabpaaaaacafaaabiaabaaapjaabaaaaac
aaaaadiaahaaoekaaeaaaaaeaaaaadiaacaaaakaaaaaoeiaaaaaobiaafaaaaad
aaaaadiaaaaaoeiaabaaoekaafaaaaadaaaaaeiaaaaaffiaacaaaakaaeaaaaae
abaaapoaaaaaiiiaajaaoekaabaaeejaaeaaaaaeacaaapoaaaaaiiiaaiaaoeka
abaaeejaaeaaaaaeadaaapoaaaaaiiiaahaadjkaabaaeejaafaaaaadaaaaapia
aaaaffjaaeaaoekaaeaaaaaeaaaaapiaadaaoekaaaaaaajaaaaaoeiaaeaaaaae
aaaaapiaafaaoekaaaaakkjaaaaaoeiaaeaaaaaeaaaaapiaagaaoekaaaaappja
aaaaoeiaaeaaaaaeaaaaadmaaaaappiaaaaaoekaaaaaoeiaabaaaaacaaaaamma
aaaaoeiaabaaaaacaaaaadoaabaaoejappppaaaafdeieefcdeacaaaaeaaaabaa
inaaaaaafjaaaaaeegiocaaaaaaaaaaaaiaaaaaafjaaaaaeegiocaaaabaaaaaa
aeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaaddcbabaaaabaaaaaaghaaaaae
pccabaaaaaaaaaaaabaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadpccabaaa
acaaaaaagfaaaaadpccabaaaadaaaaaagfaaaaadpccabaaaaeaaaaaagiaaaaac
abaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaaegiocaaaabaaaaaa
abaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaaaaaaaaaagbabaaa
aaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaa
acaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpccabaaaaaaaaaaa
egiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaaaaaaaaaadgaaaaaf
dccabaaaabaaaaaaegbabaaaabaaaaaadgaaaaagbcaabaaaaaaaaaaaakiacaaa
aaaaaaaaahaaaaaadgaaaaafccaabaaaaaaaaaaaabeaaaaaaaaaiadpdiaaaaai
dcaabaaaaaaaaaaaegaabaaaaaaaaaaaegiacaaaaaaaaaaaagaaaaaadiaaaaai
ecaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaaaaaaaaaaaahaaaaaadcaaaaam
pccabaaaacaaaaaaigaibaaaaaaaaaaaaceaaaaaaaaaaaiaaaaaeamaaaaaaaaa
aaaaeaeaegbebaaaabaaaaaadcaaaaampccabaaaadaaaaaaigaibaaaaaaaaaaa
aceaaaaaaaaaaaaaaaaaaamaaaaaaaiaaaaaaaeaegbebaaaabaaaaaadcaaaaam
pccabaaaaeaaaaaaigaibaaaaaaaaaaaaceaaaaaaaaaaaaaaaaaialpaaaaaaia
aaaaiadpegbebaaaabaaaaaadoaaaaabejfdeheoemaaaaaaacaaaaaaaiaaaaaa
diaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaaebaaaaaaaaaaaaaa
aaaaaaaaadaaaaaaabaaaaaaadadaaaafaepfdejfeejepeoaafeeffiedepepfc
eeaaklklepfdeheojiaaaaaaafaaaaaaaiaaaaaaiaaaaaaaaaaaaaaaabaaaaaa
adaaaaaaaaaaaaaaapaaaaaaimaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaa
adamaaaaimaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaaapaaaaaaimaaaaaa
acaaaaaaaaaaaaaaadaaaaaaadaaaaaaapaaaaaaimaaaaaaadaaaaaaaaaaaaaa
adaaaaaaaeaaaaaaapaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfcee
aaklklkl"
}
}
Program "fp" {
SubProgram "opengl " {
"!!GLSL"
}
SubProgram "d3d9 " {
SetTexture 0 [_MainTex] 2D 0
"ps_2_0
def c0, 0.0205000006, 0.0205000006, 0.0205000006, 0
def c1, 0.0855000019, 0.0855000019, 0.0855000019, 0
def c2, 0.231999993, 0.231999993, 0.231999993, 0
def c3, 0.324000001, 0.324000001, 0.324000001, 1
dcl_pp t0.xy
dcl_pp t1
dcl_pp t2
dcl_pp t3
dcl_2d s0
mov_pp r0.x, t1.z
mov_pp r0.y, t1.w
mov_pp r1.x, t2.z
mov_pp r1.y, t2.w
mov_pp r2.x, t3.z
mov_pp r2.y, t3.w
texld_pp r0, r0, s0
texld_pp r3, t1, s0
texld r4, t0, s0
texld_pp r1, r1, s0
texld_pp r5, t2, s0
texld_pp r2, r2, s0
texld_pp r6, t3, s0
add_pp r0, r0, r3
mul_pp r0, r0, c0
mad_pp r0, r4, c3, r0
add_pp r1, r1, r5
mad_pp r0, r1, c1, r0
add_pp r1, r2, r6
mad_pp r0, r1, c2, r0
mov_pp oC0, r0

"
}
SubProgram "d3d11 " {
SetTexture 0 [_MainTex] 2D 0
"ps_4_0
eefiecedcnalanggfhdbmlmgfgfomnpjmamipbmoabaaaaaagmadaaaaadaaaaaa
cmaaaaaammaaaaaaaaabaaaaejfdeheojiaaaaaaafaaaaaaaiaaaaaaiaaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaimaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaimaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apapaaaaimaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaaapapaaaaimaaaaaa
adaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapapaaaafdfgfpfaepfdejfeejepeoaa
feeffiedepepfceeaaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaacaaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgfheaaklkl
fdeieefcgeacaaaaeaaaaaaajjaaaaaadfbiaaaaboaaaaaajoopkhdmaaaaaaaa
aaaaaaaaaaaaaaaakabkkpdnaaaaaaaaaaaaaaaaaaaaaaaagijbgndoaaaaaaaa
aaaaaaaaaaaaaaaafeodkfdoaaaaaaaaaaaaaaaaaaaaiadpgijbgndoaaaaaaaa
aaaaaaaaaaaaaaaakabkkpdnaaaaaaaaaaaaaaaaaaaaaaaajoopkhdmaaaaaaaa
aaaaaaaaaaaaaaaafkaaaaadaagabaaaaaaaaaaafibiaaaeaahabaaaaaaaaaaa
ffffaaaagcbaaaaddcbabaaaabaaaaaagcbaaaadpcbabaaaacaaaaaagcbaaaad
pcbabaaaadaaaaaagcbaaaadpcbabaaaaeaaaaaagfaaaaadpccabaaaaaaaaaaa
giaaaaacafaaaaaaflaaaaaepcbabaaaacaaaaaaadaaaaaaefaaaaajpcaabaaa
aaaaaaaaegbabaaaabaaaaaaeghobaaaaaaaaaaaaagabaaaaaaaaaaadiaaaaak
pcaabaaaaaaaaaaaegaobaaaaaaaaaaaaceaaaaafeodkfdofeodkfdofeodkfdo
aaaaiadpdgaaaaafpcaabaaaabaaaaaaegaobaaaaaaaaaaadgaaaaafbcaabaaa
acaaaaaaabeaaaaaaaaaaaaadaaaaaabcbaaaaahccaabaaaacaaaaaaakaabaaa
acaaaaaaabeaaaaaadaaaaaaadaaaeadbkaabaaaacaaaaaaefaaaaalpcaabaaa
adaaaaaaegbanaaaacaaaaaaakaabaaaacaaaaaaeghobaaaaaaaaaaaaagabaaa
aaaaaaaaefaaaaalpcaabaaaaeaaaaaaogbknaaaacaaaaaaakaabaaaacaaaaaa
eghobaaaaaaaaaaaaagabaaaaaaaaaaaaaaaaaahpcaabaaaadaaaaaaegaobaaa
adaaaaaaegaobaaaaeaaaaaadcaaaaakpcaabaaaabaaaaaaegaobaaaadaaaaaa
agjmjaaaakaabaaaacaaaaaaegaobaaaabaaaaaaboaaaaahbcaabaaaacaaaaaa
akaabaaaacaaaaaaabeaaaaaabaaaaaabgaaaaabdgaaaaafpccabaaaaaaaaaaa
egaobaaaabaaaaaadoaaaaab"
}
SubProgram "d3d11_9x " {
SetTexture 0 [_MainTex] 2D 0
"ps_4_0_level_9_1
eefiecedhomcjagglehhdmedklabbaaojdhjjbdhabaaaaaaieafaaaaaeaaaaaa
daaaaaaaeeacaaaalaaeaaaafaafaaaaebgpgodjamacaaaaamacaaaaaaacpppp
oeabaaaaciaaaaaaaaaaciaaaaaaciaaaaaaciaaabaaceaaaaaaciaaaaaaaaaa
aaacppppfbaaaaafaaaaapkajoopkhdmjoopkhdmjoopkhdmaaaaaaaafbaaaaaf
abaaapkakabkkpdnkabkkpdnkabkkpdnaaaaaaaafbaaaaafacaaapkagijbgndo
gijbgndogijbgndoaaaaaaaafbaaaaafadaaapkafeodkfdofeodkfdofeodkfdo
aaaaiadpbpaaaaacaaaaaaiaaaaacdlabpaaaaacaaaaaaiaabaacplabpaaaaac
aaaaaaiaacaacplabpaaaaacaaaaaaiaadaacplabpaaaaacaaaaaajaaaaiapka
abaaaaacaaaacbiaabaakklaabaaaaacaaaacciaabaapplaabaaaaacabaacbia
acaakklaabaaaaacabaacciaacaapplaabaaaaacacaacbiaadaakklaabaaaaac
acaacciaadaapplaecaaaaadaaaacpiaaaaaoeiaaaaioekaecaaaaadadaacpia
abaaoelaaaaioekaecaaaaadaeaaapiaaaaaoelaaaaioekaecaaaaadabaacpia
abaaoeiaaaaioekaecaaaaadafaacpiaacaaoelaaaaioekaecaaaaadacaacpia
acaaoeiaaaaioekaecaaaaadagaacpiaadaaoelaaaaioekaacaaaaadaaaacpia
aaaaoeiaadaaoeiaafaaaaadaaaacpiaaaaaoeiaaaaaoekaaeaaaaaeaaaacpia
aeaaoeiaadaaoekaaaaaoeiaacaaaaadabaacpiaabaaoeiaafaaoeiaaeaaaaae
aaaacpiaabaaoeiaabaaoekaaaaaoeiaacaaaaadabaacpiaacaaoeiaagaaoeia
aeaaaaaeaaaacpiaabaaoeiaacaaoekaaaaaoeiaabaaaaacaaaicpiaaaaaoeia
ppppaaaafdeieefcgeacaaaaeaaaaaaajjaaaaaadfbiaaaaboaaaaaajoopkhdm
aaaaaaaaaaaaaaaaaaaaaaaakabkkpdnaaaaaaaaaaaaaaaaaaaaaaaagijbgndo
aaaaaaaaaaaaaaaaaaaaaaaafeodkfdoaaaaaaaaaaaaaaaaaaaaiadpgijbgndo
aaaaaaaaaaaaaaaaaaaaaaaakabkkpdnaaaaaaaaaaaaaaaaaaaaaaaajoopkhdm
aaaaaaaaaaaaaaaaaaaaaaaafkaaaaadaagabaaaaaaaaaaafibiaaaeaahabaaa
aaaaaaaaffffaaaagcbaaaaddcbabaaaabaaaaaagcbaaaadpcbabaaaacaaaaaa
gcbaaaadpcbabaaaadaaaaaagcbaaaadpcbabaaaaeaaaaaagfaaaaadpccabaaa
aaaaaaaagiaaaaacafaaaaaaflaaaaaepcbabaaaacaaaaaaadaaaaaaefaaaaaj
pcaabaaaaaaaaaaaegbabaaaabaaaaaaeghobaaaaaaaaaaaaagabaaaaaaaaaaa
diaaaaakpcaabaaaaaaaaaaaegaobaaaaaaaaaaaaceaaaaafeodkfdofeodkfdo
feodkfdoaaaaiadpdgaaaaafpcaabaaaabaaaaaaegaobaaaaaaaaaaadgaaaaaf
bcaabaaaacaaaaaaabeaaaaaaaaaaaaadaaaaaabcbaaaaahccaabaaaacaaaaaa
akaabaaaacaaaaaaabeaaaaaadaaaaaaadaaaeadbkaabaaaacaaaaaaefaaaaal
pcaabaaaadaaaaaaegbanaaaacaaaaaaakaabaaaacaaaaaaeghobaaaaaaaaaaa
aagabaaaaaaaaaaaefaaaaalpcaabaaaaeaaaaaaogbknaaaacaaaaaaakaabaaa
acaaaaaaeghobaaaaaaaaaaaaagabaaaaaaaaaaaaaaaaaahpcaabaaaadaaaaaa
egaobaaaadaaaaaaegaobaaaaeaaaaaadcaaaaakpcaabaaaabaaaaaaegaobaaa
adaaaaaaagjmjaaaakaabaaaacaaaaaaegaobaaaabaaaaaaboaaaaahbcaabaaa
acaaaaaaakaabaaaacaaaaaaabeaaaaaabaaaaaabgaaaaabdgaaaaafpccabaaa
aaaaaaaaegaobaaaabaaaaaadoaaaaabejfdeheojiaaaaaaafaaaaaaaiaaaaaa
iaaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaimaaaaaaaaaaaaaa
aaaaaaaaadaaaaaaabaaaaaaadadaaaaimaaaaaaabaaaaaaaaaaaaaaadaaaaaa
acaaaaaaapapaaaaimaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaaapapaaaa
imaaaaaaadaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapapaaaafdfgfpfaepfdejfe
ejepeoaafeeffiedepepfceeaaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaa
caaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgf
heaaklkl"
}
}
 }
 Pass {
  ZTest Always
  ZWrite Off
  Cull Off
  Fog { Mode Off }
  GpuProgramID 369788
Program "vp" {
SubProgram "opengl " {
"!!GLSL
#ifdef VERTEX

uniform vec4 _MainTex_TexelSize;
uniform vec4 _Parameter;
varying vec2 xlv_TEXCOORD0;
varying vec4 xlv_TEXCOORD1;
varying vec4 xlv_TEXCOORD1_1;
varying vec4 xlv_TEXCOORD1_2;
void main ()
{
  vec2 tmpvar_1;
  tmpvar_1 = ((_MainTex_TexelSize.xy * vec2(1.0, 0.0)) * _Parameter.x);
  vec4 tmpvar_2;
  tmpvar_2 = (-(tmpvar_1.xyxy) * 3.0);
  vec4 tmpvar_3;
  tmpvar_3 = (tmpvar_2 + tmpvar_1.xyxy);
  gl_Position = (gl_ModelViewProjectionMatrix * gl_Vertex);
  xlv_TEXCOORD0 = gl_MultiTexCoord0.xy;
  xlv_TEXCOORD1 = (gl_MultiTexCoord0.xyxy + (tmpvar_2 * vec4(1.0, 1.0, -1.0, -1.0)));
  xlv_TEXCOORD1_1 = (gl_MultiTexCoord0.xyxy + (tmpvar_3 * vec4(1.0, 1.0, -1.0, -1.0)));
  xlv_TEXCOORD1_2 = (gl_MultiTexCoord0.xyxy + ((tmpvar_3 + tmpvar_1.xyxy) * vec4(1.0, 1.0, -1.0, -1.0)));
}


#endif
#ifdef FRAGMENT
uniform sampler2D _MainTex;
varying vec2 xlv_TEXCOORD0;
varying vec4 xlv_TEXCOORD1;
varying vec4 xlv_TEXCOORD1_1;
varying vec4 xlv_TEXCOORD1_2;
void main ()
{
  vec4 color_1;
  color_1 = (texture2D (_MainTex, xlv_TEXCOORD0) * vec4(0.324, 0.324, 0.324, 1.0));
  color_1 = (color_1 + ((texture2D (_MainTex, xlv_TEXCOORD1.xy) + texture2D (_MainTex, xlv_TEXCOORD1.zw)) * vec4(0.0205, 0.0205, 0.0205, 0.0)));
  color_1 = (color_1 + ((texture2D (_MainTex, xlv_TEXCOORD1_1.xy) + texture2D (_MainTex, xlv_TEXCOORD1_1.zw)) * vec4(0.0855, 0.0855, 0.0855, 0.0)));
  color_1 = (color_1 + ((texture2D (_MainTex, xlv_TEXCOORD1_2.xy) + texture2D (_MainTex, xlv_TEXCOORD1_2.zw)) * vec4(0.232, 0.232, 0.232, 0.0)));
  gl_FragData[0] = color_1;
}


#endif
"
}
SubProgram "d3d9 " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
Matrix 0 [glstate_matrix_mvp]
Vector 4 [_MainTex_TexelSize]
Vector 5 [_Parameter]
"vs_2_0
def c6, 0, 1, -1, -0
def c7, -2, 0, 2, -0
def c8, -3, -0, 3, 0
dcl_position v0
dcl_texcoord v1
dp4 oPos.x, c0, v0
dp4 oPos.y, c1, v0
dp4 oPos.z, c2, v0
dp4 oPos.w, c3, v0
mov r0.xy, c6
mad r0.xy, c5.x, r0, r0.yxzw
mul r0.yz, r0.xxyw, c4.xxyw
mul r0.x, r0.y, c5.x
mad oT1, r0.xzxz, c8, v1.xyxy
mad oT2, r0.xzxz, c7, v1.xyxy
mad oT3, r0.xzxz, c6.zxyw, v1.xyxy
mov oT0.xy, v1

"
}
SubProgram "d3d11 " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 160
Vector 96 [_MainTex_TexelSize]
Vector 112 [_Parameter]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0
eefiecedchfljhdnfheliaggjbjbdolkkbjfhcdbabaaaaaafmadaaaaadaaaaaa
cmaaaaaaiaaaaaaacaabaaaaejfdeheoemaaaaaaacaaaaaaaiaaaaaadiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaaebaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaafaepfdejfeejepeoaafeeffiedepepfceeaaklkl
epfdeheojiaaaaaaafaaaaaaaiaaaaaaiaaaaaaaaaaaaaaaabaaaaaaadaaaaaa
aaaaaaaaapaaaaaaimaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaa
imaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaaapaaaaaaimaaaaaaacaaaaaa
aaaaaaaaadaaaaaaadaaaaaaapaaaaaaimaaaaaaadaaaaaaaaaaaaaaadaaaaaa
aeaaaaaaapaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaklklkl
fdeieefcdeacaaaaeaaaabaainaaaaaafjaaaaaeegiocaaaaaaaaaaaaiaaaaaa
fjaaaaaeegiocaaaabaaaaaaaeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaad
dcbabaaaabaaaaaaghaaaaaepccabaaaaaaaaaaaabaaaaaagfaaaaaddccabaaa
abaaaaaagfaaaaadpccabaaaacaaaaaagfaaaaadpccabaaaadaaaaaagfaaaaad
pccabaaaaeaaaaaagiaaaaacabaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaabaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
abaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaabaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpccabaaaaaaaaaaaegiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadgaaaaafdccabaaaabaaaaaaegbabaaaabaaaaaadgaaaaaf
ccaabaaaaaaaaaaaabeaaaaaaaaaiadpdgaaaaagecaabaaaaaaaaaaaakiacaaa
aaaaaaaaahaaaaaadiaaaaaigcaabaaaaaaaaaaafgagbaaaaaaaaaaaagibcaaa
aaaaaaaaagaaaaaadiaaaaaibcaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaaa
aaaaaaaaahaaaaaadcaaaaampccabaaaacaaaaaaigaibaaaaaaaaaaaaceaaaaa
aaaaeamaaaaaaaiaaaaaeaeaaaaaaaaaegbebaaaabaaaaaadcaaaaampccabaaa
adaaaaaaigaibaaaaaaaaaaaaceaaaaaaaaaaamaaaaaaaaaaaaaaaeaaaaaaaia
egbebaaaabaaaaaadcaaaaampccabaaaaeaaaaaaigaibaaaaaaaaaaaaceaaaaa
aaaaialpaaaaaaaaaaaaiadpaaaaaaiaegbebaaaabaaaaaadoaaaaab"
}
SubProgram "d3d11_9x " {
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
ConstBuffer "$Globals" 160
Vector 96 [_MainTex_TexelSize]
Vector 112 [_Parameter]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
BindCB  "$Globals" 0
BindCB  "UnityPerDraw" 1
"vs_4_0_level_9_1
eefiecedeffjolpcohdkglnapnhbjnnbhjnhaongabaaaaaaaeafaaaaaeaaaaaa
daaaaaaaneabaaaabaaeaaaageaeaaaaebgpgodjjmabaaaajmabaaaaaaacpopp
fmabaaaaeaaaaaaaacaaceaaaaaadmaaaaaadmaaaaaaceaaabaadmaaaaaaagaa
acaaabaaaaaaaaaaabaaaaaaaeaaadaaaaaaaaaaaaaaaaaaaaacpoppfbaaaaaf
ahaaapkaaaaaaaaaaaaaiadpaaaaialpaaaaaaiafbaaaaafaiaaapkaaaaaaama
aaaaaaaaaaaaaaeaaaaaaaiafbaaaaafajaaapkaaaaaeamaaaaaaaiaaaaaeaea
aaaaaaaabpaaaaacafaaaaiaaaaaapjabpaaaaacafaaabiaabaaapjaabaaaaac
aaaaadiaahaaoekaaeaaaaaeaaaaadiaacaaaakaaaaaoeiaaaaaobiaafaaaaad
aaaaagiaaaaanaiaabaanakaafaaaaadaaaaabiaaaaaffiaacaaaakaaeaaaaae
abaaapoaaaaaiiiaajaaoekaabaaeejaaeaaaaaeacaaapoaaaaaiiiaaiaaoeka
abaaeejaaeaaaaaeadaaapoaaaaaiiiaahaanckaabaaeejaafaaaaadaaaaapia
aaaaffjaaeaaoekaaeaaaaaeaaaaapiaadaaoekaaaaaaajaaaaaoeiaaeaaaaae
aaaaapiaafaaoekaaaaakkjaaaaaoeiaaeaaaaaeaaaaapiaagaaoekaaaaappja
aaaaoeiaaeaaaaaeaaaaadmaaaaappiaaaaaoekaaaaaoeiaabaaaaacaaaaamma
aaaaoeiaabaaaaacaaaaadoaabaaoejappppaaaafdeieefcdeacaaaaeaaaabaa
inaaaaaafjaaaaaeegiocaaaaaaaaaaaaiaaaaaafjaaaaaeegiocaaaabaaaaaa
aeaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaaddcbabaaaabaaaaaaghaaaaae
pccabaaaaaaaaaaaabaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadpccabaaa
acaaaaaagfaaaaadpccabaaaadaaaaaagfaaaaadpccabaaaaeaaaaaagiaaaaac
abaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaaegiocaaaabaaaaaa
abaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaaaaaaaaaaagbabaaa
aaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaabaaaaaa
acaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpccabaaaaaaaaaaa
egiocaaaabaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaaaaaaaaaadgaaaaaf
dccabaaaabaaaaaaegbabaaaabaaaaaadgaaaaafccaabaaaaaaaaaaaabeaaaaa
aaaaiadpdgaaaaagecaabaaaaaaaaaaaakiacaaaaaaaaaaaahaaaaaadiaaaaai
gcaabaaaaaaaaaaafgagbaaaaaaaaaaaagibcaaaaaaaaaaaagaaaaaadiaaaaai
bcaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaaaaaaaaaaaahaaaaaadcaaaaam
pccabaaaacaaaaaaigaibaaaaaaaaaaaaceaaaaaaaaaeamaaaaaaaiaaaaaeaea
aaaaaaaaegbebaaaabaaaaaadcaaaaampccabaaaadaaaaaaigaibaaaaaaaaaaa
aceaaaaaaaaaaamaaaaaaaaaaaaaaaeaaaaaaaiaegbebaaaabaaaaaadcaaaaam
pccabaaaaeaaaaaaigaibaaaaaaaaaaaaceaaaaaaaaaialpaaaaaaaaaaaaiadp
aaaaaaiaegbebaaaabaaaaaadoaaaaabejfdeheoemaaaaaaacaaaaaaaiaaaaaa
diaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaaebaaaaaaaaaaaaaa
aaaaaaaaadaaaaaaabaaaaaaadadaaaafaepfdejfeejepeoaafeeffiedepepfc
eeaaklklepfdeheojiaaaaaaafaaaaaaaiaaaaaaiaaaaaaaaaaaaaaaabaaaaaa
adaaaaaaaaaaaaaaapaaaaaaimaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaa
adamaaaaimaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaaapaaaaaaimaaaaaa
acaaaaaaaaaaaaaaadaaaaaaadaaaaaaapaaaaaaimaaaaaaadaaaaaaaaaaaaaa
adaaaaaaaeaaaaaaapaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfcee
aaklklkl"
}
}
Program "fp" {
SubProgram "opengl " {
"!!GLSL"
}
SubProgram "d3d9 " {
SetTexture 0 [_MainTex] 2D 0
"ps_2_0
def c0, 0.0205000006, 0.0205000006, 0.0205000006, 0
def c1, 0.0855000019, 0.0855000019, 0.0855000019, 0
def c2, 0.231999993, 0.231999993, 0.231999993, 0
def c3, 0.324000001, 0.324000001, 0.324000001, 1
dcl_pp t0.xy
dcl_pp t1
dcl_pp t2
dcl_pp t3
dcl_2d s0
mov_pp r0.x, t1.z
mov_pp r0.y, t1.w
mov_pp r1.x, t2.z
mov_pp r1.y, t2.w
mov_pp r2.x, t3.z
mov_pp r2.y, t3.w
texld_pp r0, r0, s0
texld_pp r3, t1, s0
texld r4, t0, s0
texld_pp r1, r1, s0
texld_pp r5, t2, s0
texld_pp r2, r2, s0
texld_pp r6, t3, s0
add_pp r0, r0, r3
mul_pp r0, r0, c0
mad_pp r0, r4, c3, r0
add_pp r1, r1, r5
mad_pp r0, r1, c1, r0
add_pp r1, r2, r6
mad_pp r0, r1, c2, r0
mov_pp oC0, r0

"
}
SubProgram "d3d11 " {
SetTexture 0 [_MainTex] 2D 0
"ps_4_0
eefiecedcnalanggfhdbmlmgfgfomnpjmamipbmoabaaaaaagmadaaaaadaaaaaa
cmaaaaaammaaaaaaaaabaaaaejfdeheojiaaaaaaafaaaaaaaiaaaaaaiaaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaimaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaimaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
apapaaaaimaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaaapapaaaaimaaaaaa
adaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapapaaaafdfgfpfaepfdejfeejepeoaa
feeffiedepepfceeaaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaacaaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgfheaaklkl
fdeieefcgeacaaaaeaaaaaaajjaaaaaadfbiaaaaboaaaaaajoopkhdmaaaaaaaa
aaaaaaaaaaaaaaaakabkkpdnaaaaaaaaaaaaaaaaaaaaaaaagijbgndoaaaaaaaa
aaaaaaaaaaaaaaaafeodkfdoaaaaaaaaaaaaaaaaaaaaiadpgijbgndoaaaaaaaa
aaaaaaaaaaaaaaaakabkkpdnaaaaaaaaaaaaaaaaaaaaaaaajoopkhdmaaaaaaaa
aaaaaaaaaaaaaaaafkaaaaadaagabaaaaaaaaaaafibiaaaeaahabaaaaaaaaaaa
ffffaaaagcbaaaaddcbabaaaabaaaaaagcbaaaadpcbabaaaacaaaaaagcbaaaad
pcbabaaaadaaaaaagcbaaaadpcbabaaaaeaaaaaagfaaaaadpccabaaaaaaaaaaa
giaaaaacafaaaaaaflaaaaaepcbabaaaacaaaaaaadaaaaaaefaaaaajpcaabaaa
aaaaaaaaegbabaaaabaaaaaaeghobaaaaaaaaaaaaagabaaaaaaaaaaadiaaaaak
pcaabaaaaaaaaaaaegaobaaaaaaaaaaaaceaaaaafeodkfdofeodkfdofeodkfdo
aaaaiadpdgaaaaafpcaabaaaabaaaaaaegaobaaaaaaaaaaadgaaaaafbcaabaaa
acaaaaaaabeaaaaaaaaaaaaadaaaaaabcbaaaaahccaabaaaacaaaaaaakaabaaa
acaaaaaaabeaaaaaadaaaaaaadaaaeadbkaabaaaacaaaaaaefaaaaalpcaabaaa
adaaaaaaegbanaaaacaaaaaaakaabaaaacaaaaaaeghobaaaaaaaaaaaaagabaaa
aaaaaaaaefaaaaalpcaabaaaaeaaaaaaogbknaaaacaaaaaaakaabaaaacaaaaaa
eghobaaaaaaaaaaaaagabaaaaaaaaaaaaaaaaaahpcaabaaaadaaaaaaegaobaaa
adaaaaaaegaobaaaaeaaaaaadcaaaaakpcaabaaaabaaaaaaegaobaaaadaaaaaa
agjmjaaaakaabaaaacaaaaaaegaobaaaabaaaaaaboaaaaahbcaabaaaacaaaaaa
akaabaaaacaaaaaaabeaaaaaabaaaaaabgaaaaabdgaaaaafpccabaaaaaaaaaaa
egaobaaaabaaaaaadoaaaaab"
}
SubProgram "d3d11_9x " {
SetTexture 0 [_MainTex] 2D 0
"ps_4_0_level_9_1
eefiecedhomcjagglehhdmedklabbaaojdhjjbdhabaaaaaaieafaaaaaeaaaaaa
daaaaaaaeeacaaaalaaeaaaafaafaaaaebgpgodjamacaaaaamacaaaaaaacpppp
oeabaaaaciaaaaaaaaaaciaaaaaaciaaaaaaciaaabaaceaaaaaaciaaaaaaaaaa
aaacppppfbaaaaafaaaaapkajoopkhdmjoopkhdmjoopkhdmaaaaaaaafbaaaaaf
abaaapkakabkkpdnkabkkpdnkabkkpdnaaaaaaaafbaaaaafacaaapkagijbgndo
gijbgndogijbgndoaaaaaaaafbaaaaafadaaapkafeodkfdofeodkfdofeodkfdo
aaaaiadpbpaaaaacaaaaaaiaaaaacdlabpaaaaacaaaaaaiaabaacplabpaaaaac
aaaaaaiaacaacplabpaaaaacaaaaaaiaadaacplabpaaaaacaaaaaajaaaaiapka
abaaaaacaaaacbiaabaakklaabaaaaacaaaacciaabaapplaabaaaaacabaacbia
acaakklaabaaaaacabaacciaacaapplaabaaaaacacaacbiaadaakklaabaaaaac
acaacciaadaapplaecaaaaadaaaacpiaaaaaoeiaaaaioekaecaaaaadadaacpia
abaaoelaaaaioekaecaaaaadaeaaapiaaaaaoelaaaaioekaecaaaaadabaacpia
abaaoeiaaaaioekaecaaaaadafaacpiaacaaoelaaaaioekaecaaaaadacaacpia
acaaoeiaaaaioekaecaaaaadagaacpiaadaaoelaaaaioekaacaaaaadaaaacpia
aaaaoeiaadaaoeiaafaaaaadaaaacpiaaaaaoeiaaaaaoekaaeaaaaaeaaaacpia
aeaaoeiaadaaoekaaaaaoeiaacaaaaadabaacpiaabaaoeiaafaaoeiaaeaaaaae
aaaacpiaabaaoeiaabaaoekaaaaaoeiaacaaaaadabaacpiaacaaoeiaagaaoeia
aeaaaaaeaaaacpiaabaaoeiaacaaoekaaaaaoeiaabaaaaacaaaicpiaaaaaoeia
ppppaaaafdeieefcgeacaaaaeaaaaaaajjaaaaaadfbiaaaaboaaaaaajoopkhdm
aaaaaaaaaaaaaaaaaaaaaaaakabkkpdnaaaaaaaaaaaaaaaaaaaaaaaagijbgndo
aaaaaaaaaaaaaaaaaaaaaaaafeodkfdoaaaaaaaaaaaaaaaaaaaaiadpgijbgndo
aaaaaaaaaaaaaaaaaaaaaaaakabkkpdnaaaaaaaaaaaaaaaaaaaaaaaajoopkhdm
aaaaaaaaaaaaaaaaaaaaaaaafkaaaaadaagabaaaaaaaaaaafibiaaaeaahabaaa
aaaaaaaaffffaaaagcbaaaaddcbabaaaabaaaaaagcbaaaadpcbabaaaacaaaaaa
gcbaaaadpcbabaaaadaaaaaagcbaaaadpcbabaaaaeaaaaaagfaaaaadpccabaaa
aaaaaaaagiaaaaacafaaaaaaflaaaaaepcbabaaaacaaaaaaadaaaaaaefaaaaaj
pcaabaaaaaaaaaaaegbabaaaabaaaaaaeghobaaaaaaaaaaaaagabaaaaaaaaaaa
diaaaaakpcaabaaaaaaaaaaaegaobaaaaaaaaaaaaceaaaaafeodkfdofeodkfdo
feodkfdoaaaaiadpdgaaaaafpcaabaaaabaaaaaaegaobaaaaaaaaaaadgaaaaaf
bcaabaaaacaaaaaaabeaaaaaaaaaaaaadaaaaaabcbaaaaahccaabaaaacaaaaaa
akaabaaaacaaaaaaabeaaaaaadaaaaaaadaaaeadbkaabaaaacaaaaaaefaaaaal
pcaabaaaadaaaaaaegbanaaaacaaaaaaakaabaaaacaaaaaaeghobaaaaaaaaaaa
aagabaaaaaaaaaaaefaaaaalpcaabaaaaeaaaaaaogbknaaaacaaaaaaakaabaaa
acaaaaaaeghobaaaaaaaaaaaaagabaaaaaaaaaaaaaaaaaahpcaabaaaadaaaaaa
egaobaaaadaaaaaaegaobaaaaeaaaaaadcaaaaakpcaabaaaabaaaaaaegaobaaa
adaaaaaaagjmjaaaakaabaaaacaaaaaaegaobaaaabaaaaaaboaaaaahbcaabaaa
acaaaaaaakaabaaaacaaaaaaabeaaaaaabaaaaaabgaaaaabdgaaaaafpccabaaa
aaaaaaaaegaobaaaabaaaaaadoaaaaabejfdeheojiaaaaaaafaaaaaaaiaaaaaa
iaaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaimaaaaaaaaaaaaaa
aaaaaaaaadaaaaaaabaaaaaaadadaaaaimaaaaaaabaaaaaaaaaaaaaaadaaaaaa
acaaaaaaapapaaaaimaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaaapapaaaa
imaaaaaaadaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapapaaaafdfgfpfaepfdejfe
ejepeoaafeeffiedepepfceeaaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaa
caaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgf
heaaklkl"
}
}
 }
}
Fallback Off
}